// FileTreeModuleTests.swift
// Generated by !CreateTests skill — review before merging

import Testing
@testable import FileTreeModule
import FoundationModule
import Foundation
import AppKit

// MARK: - Test helpers

@MainActor
private final class MockRouter: InterPanelRouter {
    var events: AsyncStream<PanelEvent> { AsyncStream { _ in } }
    var openedURLs: [URL] = []
    var syncedURLs: [URL] = []

    func open(_ file: URL) async { openedURLs.append(file) }
    func close(_ id: UUID) async {}
    func syncDirectory(_ url: URL) { syncedURLs.append(url) }
}

private func makeTempDir() throws -> URL {
    // Resolve symlinks so constructed child URLs match what FileManager.contentsOfDirectory
    // returns — on macOS, /var/folders/… symlinks to /private/var/folders/….
    let url = FileManager.default.temporaryDirectory
        .appendingPathComponent("FT-\(UUID().uuidString)")
        .standardizedFileURL
    try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
    return url
}

private func removeItem(_ url: URL) {
    try? FileManager.default.removeItem(at: url)
}

// MARK: - FileType

struct FileTypeTests {

    @Test func txt_isText() {
        #expect(FileType(url: URL(fileURLWithPath: "note.txt")) == .text)
    }

    @Test func md_isMarkdown() {
        #expect(FileType(url: URL(fileURLWithPath: "readme.md")) == .markdown)
    }

    @Test func markdownExtension_isMarkdown() {
        #expect(FileType(url: URL(fileURLWithPath: "doc.markdown")) == .markdown)
    }

    @Test func html_isHTML() {
        #expect(FileType(url: URL(fileURLWithPath: "page.html")) == .html)
    }

    @Test func htm_isHTML() {
        #expect(FileType(url: URL(fileURLWithPath: "page.htm")) == .html)
    }

    @Test func pdf_isPDF() {
        #expect(FileType(url: URL(fileURLWithPath: "spec.pdf")) == .pdf)
    }

    @Test func asc_isASCII() {
        #expect(FileType(url: URL(fileURLWithPath: "art.asc")) == .ascii)
    }

    @Test func asciiExtension_isASCII() {
        #expect(FileType(url: URL(fileURLWithPath: "art.ascii")) == .ascii)
    }

    @Test func png_isImage() {
        #expect(FileType(url: URL(fileURLWithPath: "icon.png")) == .image)
    }

    @Test func jpg_isImage() {
        #expect(FileType(url: URL(fileURLWithPath: "photo.jpg")) == .image)
    }

    @Test func jpeg_isImage() {
        #expect(FileType(url: URL(fileURLWithPath: "photo.jpeg")) == .image)
    }

    @Test func zip_isBinary() {
        #expect(FileType(url: URL(fileURLWithPath: "archive.zip")) == .binary)
    }

    @Test func swiftExtension_isUnknown() {
        #expect(FileType(url: URL(fileURLWithPath: "main.swift")) == .unknown)
    }

    @Test func uppercaseExtension_isCaseInsensitive() {
        #expect(FileType(url: URL(fileURLWithPath: "README.MD")) == .markdown)
    }
}

// MARK: - FileTreeNode

struct FileTreeNodeTests {

    private func makeNode(
        url: URL = URL(fileURLWithPath: "/tmp/test.md"),
        name: String = "test.md",
        isDirectory: Bool = false,
        children: [FileTreeNode]? = nil,
        fileType: FileType = .markdown,
        modDate: Date? = nil,
        isReadable: Bool = true
    ) -> FileTreeNode {
        FileTreeNode(
            id: url, name: name, isDirectory: isDirectory,
            children: children, fileType: fileType,
            modificationDate: modDate, isReadable: isReadable
        )
    }

    @Test func init_storesAllFields() {
        let url = URL(fileURLWithPath: "/tmp/foo.txt")
        let date = Date(timeIntervalSince1970: 1_000_000)
        let node = makeNode(url: url, name: "foo.txt", fileType: .text, modDate: date)
        #expect(node.id == url)
        #expect(node.name == "foo.txt")
        #expect(!node.isDirectory)
        #expect(node.fileType == .text)
        #expect(node.modificationDate == date)
        #expect(node.isReadable)
    }

    @Test func icon_directoryWithChildren_isFolderFill() {
        let child = makeNode()
        let node = makeNode(isDirectory: true, children: [child], fileType: .unknown)
        #expect(node.icon == "folder.fill")
    }

    @Test func icon_directoryNilChildren_isFolder() {
        let node = makeNode(isDirectory: true, children: nil, fileType: .unknown)
        #expect(node.icon == "folder")
    }

    @Test func icon_directoryEmptyChildren_isFolder() {
        let node = makeNode(isDirectory: true, children: [], fileType: .unknown)
        #expect(node.icon == "folder")
    }

    @Test func icon_unreadable_isLockDoc() {
        let node = makeNode(isReadable: false)
        #expect(node.icon == "lock.doc")
    }

    @Test func icon_markdown_isDocRichtext() {
        #expect(makeNode(fileType: .markdown).icon == "doc.richtext")
    }

    @Test func icon_html_isChevronSlash() {
        #expect(makeNode(fileType: .html).icon == "chevron.left.slash.chevron.right")
    }

    @Test func icon_pdf_isDocTextECG() {
        #expect(makeNode(fileType: .pdf).icon == "doc.text.below.ecg")
    }

    @Test func icon_ascii_isDocTextImage() {
        #expect(makeNode(fileType: .ascii).icon == "doc.text.image")
    }

    @Test func icon_text_isDocPlaintext() {
        #expect(makeNode(fileType: .text).icon == "doc.plaintext")
    }

    @Test func icon_image_isPhoto() {
        #expect(makeNode(fileType: .image).icon == "photo")
    }

    @Test func icon_binary_isDocZipper() {
        #expect(makeNode(fileType: .binary).icon == "doc.zipper")
    }

    @Test func icon_unknown_isDoc() {
        #expect(makeNode(fileType: .unknown).icon == "doc")
    }

    @Test func equatable_identicalNodes_areEqual() {
        let url = URL(fileURLWithPath: "/tmp/a.txt")
        let a = makeNode(url: url, name: "a.txt")
        let b = makeNode(url: url, name: "a.txt")
        #expect(a == b)
    }

    @Test func equatable_differentURL_isNotEqual() {
        let a = makeNode(url: URL(fileURLWithPath: "/tmp/a.txt"), name: "a.txt")
        let b = makeNode(url: URL(fileURLWithPath: "/tmp/b.txt"), name: "b.txt")
        #expect(a != b)
    }

    @Test func hashable_identicalNodes_deduplicateInSet() {
        let url = URL(fileURLWithPath: "/tmp/a.txt")
        var set = Set<FileTreeNode>()
        set.insert(makeNode(url: url, name: "a.txt"))
        set.insert(makeNode(url: url, name: "a.txt"))
        #expect(set.count == 1)
    }
}

// MARK: - FileTreeViewModel

@MainActor
struct FileTreeViewModelTests {

    private func makeVM() -> (vm: FileTreeViewModel, router: MockRouter) {
        let ws = WindowState()
        let router = MockRouter()
        let vm = FileTreeViewModel()
        vm.configure(windowState: ws, router: router)
        return (vm, router)
    }

    // MARK: Directory selection

    @Test func selectRootDirectory_setsActiveDirectory() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        #expect(vm.activeDirectory == dir)
    }

    @Test func selectRootDirectory_sameURL_doesNotResetExpandedState() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        vm.expandedNodeIDs.insert(dir)
        await vm.selectRootDirectory(dir)
        #expect(vm.expandedNodeIDs.contains(dir))
    }

    @Test func selectRootDirectory_buildsRootNode() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        #expect(vm.rootNode?.id == dir)
        #expect(vm.rootNode?.isDirectory == true)
    }

    @Test func selectRootDirectory_callsRouterSyncDirectory() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let (vm, router) = makeVM()
        await vm.selectRootDirectory(dir)
        #expect(router.syncedURLs.contains(dir))
    }

    @Test func selectRootDirectory_resetsExpansionAndSelection() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let dir2 = try makeTempDir()
        defer { removeItem(dir2) }
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        vm.expandedNodeIDs.insert(dir)
        vm.selectedNodeID = dir
        await vm.selectRootDirectory(dir2)
        #expect(vm.expandedNodeIDs.isEmpty)
        #expect(vm.selectedNodeID == nil)
    }

    // MARK: Refresh

    @Test func refreshTree_withNoDirectory_doesNothing() async {
        let (vm, _) = makeVM()
        await vm.refreshTree()
        #expect(vm.rootNode == nil)
        #expect(vm.errorMessage == nil)
    }

    @Test func refreshTree_nonExistentDir_setsErrorMessage() async throws {
        let dir = try makeTempDir()
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        removeItem(dir)
        await vm.refreshTree()
        #expect(vm.errorMessage != nil)
    }

    @Test func refreshTree_afterRecovery_clearsErrorMessage() async throws {
        let dir = try makeTempDir()
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        removeItem(dir)
        await vm.refreshTree()
        #expect(vm.errorMessage != nil)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { removeItem(dir) }
        await vm.refreshTree()
        #expect(vm.errorMessage == nil)
    }

    // MARK: Expand / collapse

    @Test func expandNode_addsToExpandedSet() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let sub = dir.appendingPathComponent("sub")
        try FileManager.default.createDirectory(at: sub, withIntermediateDirectories: false)
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        await vm.expandNode(sub)
        #expect(vm.expandedNodeIDs.contains(sub))
    }

    @Test func expandNode_loadsChildrenLazily() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let sub = dir.appendingPathComponent("sub")
        try FileManager.default.createDirectory(at: sub, withIntermediateDirectories: false)
        FileManager.default.createFile(atPath: sub.appendingPathComponent("child.txt").path, contents: nil)
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        // Use the URL from the tree (FileManager may normalise directory URLs differently).
        guard let subNodeID = vm.rootNode?.children?.first?.id else {
            Issue.record("Expected subdirectory in tree")
            return
        }
        #expect(vm.rootNode?.children?.first?.children == nil)
        await vm.expandNode(subNodeID)
        let afterExpand = vm.rootNode?.children?.first(where: { $0.id == subNodeID })
        #expect(afterExpand?.children != nil)
    }

    @Test func collapseNode_removesFromExpandedSet() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        vm.expandedNodeIDs.insert(dir)
        vm.collapseNode(dir)
        #expect(!vm.expandedNodeIDs.contains(dir))
    }

    // MARK: openNode

    @Test func openNode_directory_firstCallExpands() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        try FileManager.default.createDirectory(
            at: dir.appendingPathComponent("sub"), withIntermediateDirectories: false)
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        guard let subID = vm.rootNode?.children?.first?.id else {
            Issue.record("Expected subdirectory in tree")
            return
        }
        await vm.openNode(subID)
        #expect(vm.expandedNodeIDs.contains(subID))
    }

    @Test func openNode_directory_secondCallCollapses() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        try FileManager.default.createDirectory(
            at: dir.appendingPathComponent("sub"), withIntermediateDirectories: false)
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        guard let subID = vm.rootNode?.children?.first?.id else {
            Issue.record("Expected subdirectory in tree")
            return
        }
        await vm.openNode(subID)  // expands
        await vm.openNode(subID)  // collapses
        #expect(!vm.expandedNodeIDs.contains(subID))
    }

    @Test func openNode_file_callsRouter() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        FileManager.default.createFile(atPath: dir.appendingPathComponent("note.md").path, contents: nil)
        let (vm, router) = makeVM()
        await vm.selectRootDirectory(dir)
        guard let fileID = vm.rootNode?.children?.first?.id else {
            Issue.record("Expected file in tree")
            return
        }
        await vm.openNode(fileID)
        #expect(router.openedURLs.contains(fileID))
    }

    // MARK: File operations

    @Test func createFile_createsFileOnDisk() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        await vm.createFile(named: "new.txt", in: dir)
        #expect(FileManager.default.fileExists(atPath: dir.appendingPathComponent("new.txt").path))
    }

    @Test func createFile_refreshesTree() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        #expect(vm.rootNode?.children?.count == 0)
        await vm.createFile(named: "added.txt", in: dir)
        #expect(vm.rootNode?.children?.count == 1)
    }

    @Test func createFolder_createsDirOnDisk() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        await vm.createFolder(named: "NewFolder", in: dir)
        var isDir: ObjCBool = false
        let exists = FileManager.default.fileExists(
            atPath: dir.appendingPathComponent("NewFolder").path, isDirectory: &isDir)
        #expect(exists && isDir.boolValue)
    }

    @Test func rename_movesFileOnDisk() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let file = dir.appendingPathComponent("old.txt")
        FileManager.default.createFile(atPath: file.path, contents: nil)
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        await vm.rename(nodeID: file, to: "new.txt")
        #expect(!FileManager.default.fileExists(atPath: file.path))
        #expect(FileManager.default.fileExists(atPath: dir.appendingPathComponent("new.txt").path))
    }

    @Test func rename_emptyName_doesNothing() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let file = dir.appendingPathComponent("keep.txt")
        FileManager.default.createFile(atPath: file.path, contents: nil)
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        await vm.rename(nodeID: file, to: "   ")
        #expect(FileManager.default.fileExists(atPath: file.path))
    }

    @Test func rename_updatesSelectedNodeID() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let file = dir.appendingPathComponent("before.txt")
        FileManager.default.createFile(atPath: file.path, contents: nil)
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        vm.selectedNodeID = file
        await vm.rename(nodeID: file, to: "after.txt")
        #expect(vm.selectedNodeID == dir.appendingPathComponent("after.txt"))
    }

    @Test func trash_clearsSelectedNodeID() async throws {
        let dir = try makeTempDir()
        defer { removeItem(dir) }
        let file = dir.appendingPathComponent("toTrash.txt")
        FileManager.default.createFile(atPath: file.path, contents: nil)
        let (vm, _) = makeVM()
        await vm.selectRootDirectory(dir)
        vm.selectedNodeID = file
        await vm.trash(nodeID: file)
        #expect(vm.selectedNodeID == nil)
    }

    // MARK: Search / filtering

    @Test func displayedChildren_nilChildren_returnsEmpty() {
        let (vm, _) = makeVM()
        let node = FileTreeNode(
            id: URL(fileURLWithPath: "/tmp/a"), name: "a",
            isDirectory: true, children: nil,
            fileType: .unknown, modificationDate: nil, isReadable: true)
        #expect(vm.displayedChildren(for: node).isEmpty)
    }

    @Test func displayedChildren_emptySearch_returnsAll() {
        let (vm, _) = makeVM()
        vm.searchText = ""
        let children = [
            FileTreeNode(id: URL(fileURLWithPath: "/tmp/a.txt"), name: "a.txt",
                         isDirectory: false, children: nil, fileType: .text,
                         modificationDate: nil, isReadable: true),
            FileTreeNode(id: URL(fileURLWithPath: "/tmp/b.txt"), name: "b.txt",
                         isDirectory: false, children: nil, fileType: .text,
                         modificationDate: nil, isReadable: true),
        ]
        let parent = FileTreeNode(
            id: URL(fileURLWithPath: "/tmp"), name: "tmp",
            isDirectory: true, children: children,
            fileType: .unknown, modificationDate: nil, isReadable: true)
        #expect(vm.displayedChildren(for: parent).count == 2)
    }

    @Test func displayedChildren_search_filtersMatching() {
        let (vm, _) = makeVM()
        vm.searchText = "notes"
        let children = [
            FileTreeNode(id: URL(fileURLWithPath: "/tmp/notes.md"), name: "notes.md",
                         isDirectory: false, children: nil, fileType: .markdown,
                         modificationDate: nil, isReadable: true),
            FileTreeNode(id: URL(fileURLWithPath: "/tmp/readme.txt"), name: "readme.txt",
                         isDirectory: false, children: nil, fileType: .text,
                         modificationDate: nil, isReadable: true),
        ]
        let parent = FileTreeNode(
            id: URL(fileURLWithPath: "/tmp"), name: "tmp",
            isDirectory: true, children: children,
            fileType: .unknown, modificationDate: nil, isReadable: true)
        let result = vm.displayedChildren(for: parent)
        #expect(result.count == 1)
        #expect(result.first?.name == "notes.md")
    }

    @Test func displayedChildren_search_includesDirectoryWithMatchingDescendant() {
        let (vm, _) = makeVM()
        vm.searchText = "target"
        let grandchild = FileTreeNode(
            id: URL(fileURLWithPath: "/tmp/dir/target.md"), name: "target.md",
            isDirectory: false, children: nil, fileType: .markdown,
            modificationDate: nil, isReadable: true)
        let subdir = FileTreeNode(
            id: URL(fileURLWithPath: "/tmp/dir"), name: "dir",
            isDirectory: true, children: [grandchild],
            fileType: .unknown, modificationDate: nil, isReadable: true)
        let unrelated = FileTreeNode(
            id: URL(fileURLWithPath: "/tmp/other.txt"), name: "other.txt",
            isDirectory: false, children: nil, fileType: .text,
            modificationDate: nil, isReadable: true)
        let parent = FileTreeNode(
            id: URL(fileURLWithPath: "/tmp"), name: "tmp",
            isDirectory: true, children: [subdir, unrelated],
            fileType: .unknown, modificationDate: nil, isReadable: true)
        let result = vm.displayedChildren(for: parent)
        #expect(result.count == 1)
        #expect(result.first?.name == "dir")
    }
}

// MARK: - FileSystemWatcher

struct FileSystemWatcherTests {

    @Test func init_setsURL() {
        let url = URL(fileURLWithPath: "/tmp/watchtest")
        let watcher = FileSystemWatcher(url: url)
        defer { watcher.stop() }
        #expect(watcher.presentedItemURL == url)
    }

    @Test func stop_finishesStream() async {
        let watcher = FileSystemWatcher(url: URL(fileURLWithPath: "/tmp/watchtest"))
        watcher.stop()
        var count = 0
        for await _ in watcher.changeStream { count += 1 }
        #expect(count == 0)
    }

    @Test func presentedSubitemDidChange_emitsURL() async {
        let watcher = FileSystemWatcher(url: URL(fileURLWithPath: "/tmp/watchtest"))
        defer { watcher.stop() }
        let changed = URL(fileURLWithPath: "/tmp/watchtest/file.txt")
        watcher.presentedSubitemDidChange(at: changed)
        var received: URL?
        for await url in watcher.changeStream { received = url; break }
        #expect(received == changed)
    }

    @Test func presentedSubitemDidAppear_emitsURL() async {
        let watcher = FileSystemWatcher(url: URL(fileURLWithPath: "/tmp/watchtest"))
        defer { watcher.stop() }
        let appeared = URL(fileURLWithPath: "/tmp/watchtest/new.txt")
        watcher.presentedSubitemDidAppear(at: appeared)
        var received: URL?
        for await url in watcher.changeStream { received = url; break }
        #expect(received == appeared)
    }

    @Test func presentedItemDidChange_emitsWatchedURL() async {
        let base = URL(fileURLWithPath: "/tmp/watchtest")
        let watcher = FileSystemWatcher(url: base)
        defer { watcher.stop() }
        watcher.presentedItemDidChange()
        var received: URL?
        for await url in watcher.changeStream { received = url; break }
        #expect(received == base)
    }

    @Test func accommodateDeletion_callsCompletionWithNoError() async {
        let watcher = FileSystemWatcher(url: URL(fileURLWithPath: "/tmp/watchtest"))
        defer { watcher.stop() }
        var completionError: Error? = NSError(domain: "sentinel", code: 0)
        await withCheckedContinuation { (cont: CheckedContinuation<Void, Never>) in
            watcher.accommodatePresentedItemDeletion { error in
                completionError = error
                cont.resume()
            }
        }
        #expect(completionError == nil)
    }
}
