// TerminalModuleTests.swift
// Generated by !CreateTests skill — review before merging

import Testing
@testable import TerminalModule
import Foundation

// MARK: - TerminalOp extraction helpers
// TerminalOp is Sendable but not Equatable; these helpers let us assert on
// individual cases without manually pattern-matching in every test body.

extension TerminalOp {
    var printedChar: Character?               { if case .print(let c)  = self { return c };  return nil }
    var isBell: Bool                          { if case .bell           = self { return true }; return false }
    var isBackspace: Bool                     { if case .backspace      = self { return true }; return false }
    var isTab: Bool                           { if case .tab            = self { return true }; return false }
    var isNewline: Bool                       { if case .newline        = self { return true }; return false }
    var isCarriageReturn: Bool                { if case .carriageReturn = self { return true }; return false }
    var isSaveCursor: Bool                    { if case .saveCursor     = self { return true }; return false }
    var isRestoreCursor: Bool                 { if case .restoreCursor  = self { return true }; return false }
    var isEnterAltScreen: Bool                { if case .enterAltScreen = self { return true }; return false }
    var isExitAltScreen: Bool                 { if case .exitAltScreen  = self { return true }; return false }
    var sgrAttrs: [SGRAttribute]?             { if case .setAttributes(let a) = self { return a }; return nil }
    var eraseDisplayMode: EraseMode?          { if case .eraseDisplay(let m)  = self { return m }; return nil }
    var eraseLineMode: EraseMode?             { if case .eraseLine(let m)     = self { return m }; return nil }
    var moveCursorPos: (row: Int, col: Int)?  { if case .moveCursor(let r, let c) = self { return (r, c) }; return nil }
    var relDelta: (rows: Int, cols: Int)?     { if case .moveCursorRelative(let r, let c) = self { return (r, c) }; return nil }
    var setCursorColValue: Int?               { if case .setCursorCol(let c) = self { return c }; return nil }
    var setCursorRowValue: Int?               { if case .setCursorRow(let r) = self { return r }; return nil }
    var scrollUpCount: Int?                   { if case .scrollUp(let n)     = self { return n }; return nil }
    var titleValue: String?                   { if case .setTitle(let t)     = self { return t }; return nil }
    var cursorVisibility: Bool?               { if case .setCursorVisible(let v) = self { return v }; return nil }
}

// MARK: - Shared parse helpers

private func parse(_ string: String) -> [TerminalOp] {
    var p = ANSIParser()
    return p.parse(Data(string.utf8))
}

// MARK: - ANSIParserTests

struct ANSIParserTests {

    // MARK: Happy Path — ground-state control codes

    @Test func parserEmitsPrintForPrintableASCII() {
        let ops = parse("A")
        #expect(ops.first?.printedChar == "A")
    }

    @Test func parserEmitsBellFor0x07() {
        let ops = parse("\u{07}")
        #expect(ops.first?.isBell == true)
    }

    @Test func parserEmitsBackspaceFor0x08() {
        let ops = parse("\u{08}")
        #expect(ops.first?.isBackspace == true)
    }

    @Test func parserEmitsTabFor0x09() {
        let ops = parse("\u{09}")
        #expect(ops.first?.isTab == true)
    }

    @Test func parserEmitsNewlineForLF() {
        let ops = parse("\u{0A}")
        #expect(ops.first?.isNewline == true)
    }

    @Test func parserEmitsCarriageReturnFor0x0D() {
        let ops = parse("\u{0D}")
        #expect(ops.first?.isCarriageReturn == true)
    }

    // MARK: Happy Path — ESC sequences

    @Test func parserEmitsSaveCursorForESC7() {
        let ops = parse("\u{1B}7")
        #expect(ops.first?.isSaveCursor == true)
    }

    @Test func parserEmitsRestoreCursorForESC8() {
        let ops = parse("\u{1B}8")
        #expect(ops.first?.isRestoreCursor == true)
    }

    @Test func parserEmitsNewlineForESCD() {
        let ops = parse("\u{1B}D")  // IND
        #expect(ops.first?.isNewline == true)
    }

    @Test func parserEmitsScrollUp1ForESCM() {
        let ops = parse("\u{1B}M")  // RI
        #expect(ops.first?.scrollUpCount == 1)
    }

    // MARK: Happy Path — CSI cursor movement

    @Test func parserCUUMovesRelativelyUp() {
        let ops = parse("\u{1B}[3A")  // CUU 3
        #expect(ops.first?.relDelta?.rows == -3)
        #expect(ops.first?.relDelta?.cols == 0)
    }

    @Test func parserCUUDefaultsToOneRow() {
        let ops = parse("\u{1B}[A")  // CUU with no param
        #expect(ops.first?.relDelta?.rows == -1)
    }

    @Test func parserCUPPositionsCursorAbsolutely() {
        let ops = parse("\u{1B}[3;7H")  // CUP row=3 col=7 (1-based)
        #expect(ops.first?.moveCursorPos?.row == 2)
        #expect(ops.first?.moveCursorPos?.col == 6)
    }

    @Test func parserCUPWithNoParamsMovesToOrigin() {
        let ops = parse("\u{1B}[H")
        #expect(ops.first?.moveCursorPos?.row == 0)
        #expect(ops.first?.moveCursorPos?.col == 0)
    }

    @Test func parserCHASetsColumnZeroBased() {
        let ops = parse("\u{1B}[5G")  // CHA col=5 (1-based) → 4
        #expect(ops.first?.setCursorColValue == 4)
    }

    @Test func parserVPASetsRowZeroBased() {
        let ops = parse("\u{1B}[5d")  // VPA row=5 (1-based) → 4
        #expect(ops.first?.setCursorRowValue == 4)
    }

    // MARK: Happy Path — CSI erase

    @Test func parserEDWithNoParamErasesToEnd() {
        let ops = parse("\u{1B}[J")
        #expect(ops.first?.eraseDisplayMode == .toEnd)
    }

    @Test func parserEDParam1ErasesToStart() {
        let ops = parse("\u{1B}[1J")
        #expect(ops.first?.eraseDisplayMode == .toStart)
    }

    @Test func parserEDParam2ErasesAll() {
        let ops = parse("\u{1B}[2J")
        #expect(ops.first?.eraseDisplayMode == .all)
    }

    @Test func parserELParam2ErasesEntireLine() {
        let ops = parse("\u{1B}[2K")
        #expect(ops.first?.eraseLineMode == .all)
    }

    // MARK: Happy Path — CSI SGR attributes

    @Test func parserSGREmptyParamEmitsReset() {
        let ops = parse("\u{1B}[m")  // no param → reset
        #expect(ops.first?.sgrAttrs == [.reset])
    }

    @Test func parserSGR1EmitsBold() {
        let ops = parse("\u{1B}[1m")
        #expect(ops.first?.sgrAttrs == [.bold])
    }

    @Test func parserSGRForegroundANSIColor() {
        let ops = parse("\u{1B}[31m")  // red foreground
        #expect(ops.first?.sgrAttrs == [.foreground(.ansi(1))])
    }

    @Test func parserSGRBrightForeground() {
        let ops = parse("\u{1B}[91m")  // bright red foreground
        #expect(ops.first?.sgrAttrs == [.foreground(.ansi(9))])
    }

    @Test func parserSGR256ColorForeground() {
        let ops = parse("\u{1B}[38;5;200m")
        #expect(ops.first?.sgrAttrs == [.foreground(.palette(200))])
    }

    @Test func parserSGRTrueColorForeground() {
        let ops = parse("\u{1B}[38;2;255;128;0m")
        guard let attrs = ops.first?.sgrAttrs, let attr = attrs.first else {
            Issue.record("Expected one SGR attribute")
            return
        }
        if case .foreground(.rgb(let r, let g, let b)) = attr {
            #expect(r == 1.0)
            #expect(abs(g - 128.0 / 255.0) < 0.001)
            #expect(b == 0.0)
        } else {
            Issue.record("Expected .foreground(.rgb(...))")
        }
    }

    // MARK: Happy Path — DEC private modes

    @Test func parserHidesCursorViaDECPrivate25l() {
        let ops = parse("\u{1B}[?25l")
        #expect(ops.first?.cursorVisibility == false)
    }

    @Test func parserShowsCursorViaDECPrivate25h() {
        let ops = parse("\u{1B}[?25h")
        #expect(ops.first?.cursorVisibility == true)
    }

    @Test func parserEntersAltScreenVia1049h() {
        let ops = parse("\u{1B}[?1049h")
        #expect(ops.first?.isEnterAltScreen == true)
    }

    @Test func parserExitsAltScreenVia1049l() {
        let ops = parse("\u{1B}[?1049l")
        #expect(ops.first?.isExitAltScreen == true)
    }

    // MARK: Happy Path — OSC

    @Test func parserSetsTitleViaOSCBEL() {
        let ops = parse("\u{1B}]0;My Shell\u{07}")
        #expect(ops.first?.titleValue == "My Shell")
    }

    @Test func parserSetsTitleViaOSCStringTerminator() {
        // ESC ] 2 ; Hello ESC \
        let ops = parse("\u{1B}]2;Hello\u{1B}\\")
        #expect(ops.first?.titleValue == "Hello")
    }

    // MARK: Edge Cases

    @Test func parserReturnsEmptyOpsForEmptyInput() {
        let ops = parse("")
        #expect(ops.isEmpty)
    }

    @Test func parserDoesNotCrashOnTruncatedESC() {
        let ops = parse("\u{1B}")  // ESC with no following byte
        #expect(ops.isEmpty)
    }

    @Test func parserDoesNotCrashOnTruncatedCSI() {
        let ops = parse("\u{1B}[")  // ESC [ with no final byte
        #expect(ops.isEmpty)
    }

    @Test func parserIgnoresUnknownESCSequence() {
        let ops = parse("\u{1B}Z")  // ESC Z is not defined
        #expect(ops.isEmpty)
    }

    @Test func parserIgnoresUnknownCSIFinalByte() {
        let ops = parse("\u{1B}[99X")  // 0x58 = 'X', not handled
        #expect(ops.isEmpty)
    }

    @Test func parserSkipsC0ControlsBelow0x20() {
        // 0x01 (SOH) is not a known control — should produce no ops
        var p = ANSIParser()
        let ops = p.parse(Data([0x01]))
        #expect(ops.isEmpty)
    }

    @Test func parserScrollUpCSIUsesParam() {
        let ops = parse("\u{1B}[4S")
        #expect(ops.first?.scrollUpCount == 4)
    }
}

// MARK: - TerminalEmulatorTests

struct TerminalEmulatorTests {

    // MARK: Happy Path

    @Test func emulatorCursorStartsAtOrigin() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        let snap = await emu.snapshot()
        #expect(snap.cursorRow == 0)
        #expect(snap.cursorCol == 0)
    }

    @Test func emulatorCursorIsVisibleInitially() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        let snap = await emu.snapshot()
        #expect(snap.cursorVisible == true)
    }

    @Test func emulatorGridHasCorrectInitialDimensions() async {
        let emu = TerminalEmulator(cols: 10, rows: 5)
        let snap = await emu.snapshot()
        #expect(snap.grid.count == 5)
        #expect(snap.grid[0].count == 10)
    }

    @Test func emulatorPrintedCharacterAppearsInGrid() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("X".utf8))
        let snap = await emu.snapshot()
        #expect(snap.grid[0][0].character == "X")
    }

    @Test func emulatorCursorAdvancesAfterPrint() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("AB".utf8))
        let snap = await emu.snapshot()
        #expect(snap.cursorCol == 2)
    }

    @Test func emulatorNewlineAdvancesCursorRow() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("A\nB".utf8))
        let snap = await emu.snapshot()
        #expect(snap.cursorRow == 1)
    }

    @Test func emulatorCarriageReturnSetsCursorColToZero() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("HELLO\rX".utf8))
        let snap = await emu.snapshot()
        // X overwrote position 0 after carriage return
        #expect(snap.grid[0][0].character == "X")
    }

    @Test func emulatorBackspaceDecrementsCursorCol() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("AB\u{08}".utf8))  // print A, B, then backspace
        let snap = await emu.snapshot()
        #expect(snap.cursorCol == 1)
    }

    @Test func emulatorSetTitlePropagatesViaSnapshot() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("\u{1B}]0;TestTitle\u{07}".utf8))
        let snap = await emu.snapshot()
        #expect(snap.title == "TestTitle")
    }

    @Test func emulatorSetCursorInvisiblePropagatesViaSnapshot() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("\u{1B}[?25l".utf8))
        let snap = await emu.snapshot()
        #expect(snap.cursorVisible == false)
    }

    @Test func emulatorScrollbackGrowsWhenScreenFills() async {
        let emu = TerminalEmulator(cols: 4, rows: 2)
        // CRLF resets cursor column; second CRLF pushes the first row into scrollback.
        await emu.feed(Data("AAAA\r\nBBBB\r\n".utf8))
        let snap = await emu.snapshot()
        #expect(snap.scrollback.count == 1)
    }

    @Test func emulatorResizePreservesExistingContent() async {
        let emu = TerminalEmulator(cols: 10, rows: 5)
        await emu.feed(Data("Hello".utf8))
        await emu.resize(cols: 20, rows: 10)
        let snap = await emu.snapshot()
        #expect(snap.grid[0][0].character == "H")
    }

    @Test func emulatorResizeClampsCursorToNewBounds() async {
        let emu = TerminalEmulator(cols: 10, rows: 10)
        await emu.feed(Data("\u{1B}[8;1H".utf8))  // CUP row=8, col=1 → (7, 0)
        await emu.resize(cols: 10, rows: 5)
        let snap = await emu.snapshot()
        #expect(snap.cursorRow <= 4)
    }

    @Test func emulatorResetClearsGridAndCursor() async {
        let emu = TerminalEmulator(cols: 10, rows: 5)
        await emu.feed(Data("ABC".utf8))
        await emu.reset()
        let snap = await emu.snapshot()
        #expect(snap.grid[0][0].character == " ")
        #expect(snap.cursorRow == 0)
        #expect(snap.cursorCol == 0)
    }

    @Test func emulatorAltScreenEnterClearsGrid() async {
        let emu = TerminalEmulator(cols: 10, rows: 5)
        await emu.feed(Data("HELLO".utf8))
        await emu.feed(Data("\u{1B}[?1049h".utf8))  // enter alt screen
        let snap = await emu.snapshot()
        #expect(snap.grid[0][0].character == " ")
    }

    @Test func emulatorAltScreenExitRestoresContent() async {
        let emu = TerminalEmulator(cols: 10, rows: 5)
        await emu.feed(Data("HELLO".utf8))
        await emu.feed(Data("\u{1B}[?1049h".utf8))  // enter alt screen
        await emu.feed(Data("WORLD".utf8))           // alt-screen content
        await emu.feed(Data("\u{1B}[?1049l".utf8))  // exit alt screen
        let snap = await emu.snapshot()
        #expect(snap.grid[0][0].character == "H")
    }
}

// MARK: - ScrollbackBufferTests

struct ScrollbackBufferTests {

    private func makeRow(_ char: Character, width: Int = 1) -> [ScreenCell] {
        [ScreenCell](repeating: ScreenCell(character: char), count: width)
    }

    // MARK: Happy Path

    @Test func scrollbackBufferStartsEmpty() {
        let buf = ScrollbackBuffer(capacity: 10)
        #expect(buf.lineCount == 0)
    }

    @Test func scrollbackBufferLinesIsEmptyInitially() {
        let buf = ScrollbackBuffer(capacity: 10)
        #expect(buf.lines().isEmpty)
    }

    @Test func scrollbackBufferLineCountGrowsOnAppend() {
        var buf = ScrollbackBuffer(capacity: 10)
        buf.append(makeRow("A"))
        buf.append(makeRow("B"))
        #expect(buf.lineCount == 2)
    }

    @Test func scrollbackBufferLinesReturnsInAppendOrder() {
        var buf = ScrollbackBuffer(capacity: 5)
        buf.append(makeRow("A"))
        buf.append(makeRow("B"))
        buf.append(makeRow("C"))
        let lines = buf.lines()
        #expect(lines[0].first?.character == "A")
        #expect(lines[1].first?.character == "B")
        #expect(lines[2].first?.character == "C")
    }

    @Test func scrollbackBufferCapacityIsRespected() {
        var buf = ScrollbackBuffer(capacity: 3)
        buf.append(makeRow("A"))
        buf.append(makeRow("B"))
        buf.append(makeRow("C"))
        buf.append(makeRow("D"))  // overflows — evicts A
        #expect(buf.lineCount == 3)
    }

    @Test func scrollbackBufferEvictsOldestLineOnOverflow() {
        var buf = ScrollbackBuffer(capacity: 3)
        buf.append(makeRow("A"))
        buf.append(makeRow("B"))
        buf.append(makeRow("C"))
        buf.append(makeRow("D"))  // evicts A
        let lines = buf.lines()
        #expect(lines.first?.first?.character == "B")
    }

    @Test func scrollbackBufferPreservesOldestToNewestOrderAfterWrap() {
        var buf = ScrollbackBuffer(capacity: 3)
        for ch: Character in ["A", "B", "C", "D"] { buf.append(makeRow(ch)) }
        let chars = buf.lines().compactMap { $0.first?.character }
        #expect(chars == ["B", "C", "D"])
    }

    @Test func scrollbackBufferClearResetsLineCount() {
        var buf = ScrollbackBuffer(capacity: 5)
        buf.append(makeRow("X"))
        buf.append(makeRow("Y"))
        buf.clear()
        #expect(buf.lineCount == 0)
    }

    @Test func scrollbackBufferClearMakesLinesEmpty() {
        var buf = ScrollbackBuffer(capacity: 5)
        buf.append(makeRow("X"))
        buf.clear()
        #expect(buf.lines().isEmpty)
    }

    // MARK: Edge Cases

    @Test func scrollbackBufferCapacityOneKeepsOnlyLastLine() {
        var buf = ScrollbackBuffer(capacity: 1)
        buf.append(makeRow("A"))
        buf.append(makeRow("B"))
        buf.append(makeRow("C"))
        let lines = buf.lines()
        #expect(lines.count == 1)
        #expect(lines.first?.first?.character == "C")
    }
}

// MARK: - KeyEncoderTests

private func makeKey(
    code: UInt16,
    chars: String,
    modifiers: TerminalModifiers = []
) -> TerminalKeyEvent {
    TerminalKeyEvent(keyCode: code, characters: chars, modifiers: modifiers)
}

struct KeyEncoderTests {

    // MARK: Happy Path — printable characters

    @Test func keyEncoderPassesThroughPrintableASCII() {
        let result = KeyEncoder.encode(makeKey(code: 0, chars: "a"))
        #expect(result == Data("a".utf8))
    }

    @Test func keyEncoderPassesThroughSpaceCharacter() {
        let result = KeyEncoder.encode(makeKey(code: 0, chars: " "))
        #expect(result == Data(" ".utf8))
    }

    // MARK: Happy Path — Ctrl combos

    @Test func keyEncoderCtrlCProduces0x03() {
        let result = KeyEncoder.encode(makeKey(code: 0, chars: "c", modifiers: .control))
        #expect(result == Data([0x03]))
    }

    @Test func keyEncoderCtrlAProduces0x01() {
        let result = KeyEncoder.encode(makeKey(code: 0, chars: "a", modifiers: .control))
        #expect(result == Data([0x01]))
    }

    @Test func keyEncoderCtrlZProduces0x1A() {
        let result = KeyEncoder.encode(makeKey(code: 0, chars: "z", modifiers: .control))
        #expect(result == Data([0x1A]))
    }

    // MARK: Happy Path — special keys

    @Test func keyEncoderReturnProducesCR() {
        let result = KeyEncoder.encode(makeKey(code: 36, chars: "\r"))
        #expect(result == Data([0x0D]))
    }

    @Test func keyEncoderTabProduces0x09() {
        let result = KeyEncoder.encode(makeKey(code: 48, chars: "\t"))
        #expect(result == Data([0x09]))
    }

    @Test func keyEncoderShiftTabProducesBackTabSequence() {
        let result = KeyEncoder.encode(makeKey(code: 48, chars: "\t", modifiers: .shift))
        #expect(result == Data([0x1B, 0x5B, 0x5A]))  // ESC [ Z
    }

    @Test func keyEncoderDeleteProduces0x7F() {
        let result = KeyEncoder.encode(makeKey(code: 51, chars: "\u{7F}"))
        #expect(result == Data([0x7F]))
    }

    @Test func keyEncoderEscapeProduces0x1B() {
        let result = KeyEncoder.encode(makeKey(code: 53, chars: "\u{1B}"))
        #expect(result == Data([0x1B]))
    }

    @Test func keyEncoderForwardDeleteProducesVT220Sequence() {
        let result = KeyEncoder.encode(makeKey(code: 117, chars: ""))
        #expect(result == Data([0x1B, 0x5B, 0x33, 0x7E]))  // ESC [ 3 ~
    }

    @Test func keyEncoderUpArrowProducesCursorUpSequence() {
        let result = KeyEncoder.encode(makeKey(code: 126, chars: ""))
        #expect(result == Data([0x1B, 0x5B, 0x41]))  // ESC [ A
    }

    @Test func keyEncoderShiftUpArrowProducesShiftedSequence() {
        let result = KeyEncoder.encode(makeKey(code: 126, chars: "", modifiers: .shift))
        // ESC [ 1 ; 2 A
        #expect(result == Data([0x1B, 0x5B, 0x31, 0x3B, 0x32, 0x41]))
    }

    @Test func keyEncoderLeftArrowProducesCursorBackSequence() {
        let result = KeyEncoder.encode(makeKey(code: 123, chars: ""))
        #expect(result == Data([0x1B, 0x5B, 0x44]))  // ESC [ D
    }

    @Test func keyEncoderHomeProducesCursorHomeSequence() {
        let result = KeyEncoder.encode(makeKey(code: 115, chars: ""))
        #expect(result == Data([0x1B, 0x5B, 0x48]))  // ESC [ H
    }

    @Test func keyEncoderOptionHomeProducesVT220HomeSequence() {
        let result = KeyEncoder.encode(makeKey(code: 115, chars: "", modifiers: .option))
        #expect(result == Data([0x1B, 0x5B, 0x31, 0x7E]))  // ESC [ 1 ~
    }

    @Test func keyEncoderPageUpProducesVT220PageUpSequence() {
        let result = KeyEncoder.encode(makeKey(code: 116, chars: ""))
        #expect(result == Data([0x1B, 0x5B, 0x35, 0x7E]))  // ESC [ 5 ~
    }

    // MARK: Error Conditions

    @Test func keyEncoderCommandKeyComboReturnsNil() {
        let result = KeyEncoder.encode(makeKey(code: 0, chars: "a", modifiers: .command))
        #expect(result == nil)
    }

    @Test func keyEncoderEmptyCharsWithNoSpecialKeyReturnsNil() {
        let result = KeyEncoder.encode(makeKey(code: 9999, chars: ""))
        #expect(result == nil)
    }
}

// MARK: - TerminalModifiersTests

struct TerminalModifiersTests {

    @Test func terminalModifiersControlFlagIsSet() {
        let mods = TerminalModifiers.control
        #expect(mods.contains(.control))
    }

    @Test func terminalModifiersCombinedContainsBothFlags() {
        let mods: TerminalModifiers = [.control, .shift]
        #expect(mods.contains(.shift))
    }

    @Test func terminalModifiersDoesNotContainUnrelatedFlag() {
        let mods = TerminalModifiers.control
        #expect(!mods.contains(.shift))
    }

    @Test func terminalModifiersEmptySetContainsNoFlag() {
        let mods: TerminalModifiers = []
        #expect(!mods.contains(.control))
    }
}

// MARK: - ScreenCellTests

struct ScreenCellTests {

    @Test func screenCellBlankHasSpaceCharacter() {
        #expect(ScreenCell.blank.character == " ")
    }

    @Test func screenCellDefaultInitMatchesBlank() {
        #expect(ScreenCell() == ScreenCell.blank)
    }

    @Test func screenCellCustomCharacterIsStored() {
        let cell = ScreenCell(character: "Z")
        #expect(cell.character == "Z")
    }

    @Test func screenCellForegroundColorIsStored() {
        let cell = ScreenCell(foreground: .ansi(2))
        #expect(cell.foreground == .ansi(2))
    }

    // MARK: CellStyle

    @Test func cellStylePlainHasAllFlagsFalse() {
        let style = CellStyle.plain
        #expect(!style.bold && !style.italic && !style.underline)
    }

    @Test func cellStyleMutationIsReflected() {
        var style = CellStyle.plain
        style.bold = true
        #expect(style.bold)
    }
}

// MARK: - TerminalProfileTests

struct TerminalProfileTests {

    @Test func terminalProfileDefaultFontNameIsMenlo() {
        #expect(TerminalProfile.default.fontName == "Menlo")
    }

    @Test func terminalProfileDefaultFontSizeIs13() {
        #expect(TerminalProfile.default.fontSize == 13.0)
    }

    @Test func terminalProfileDefaultScrollbackLimitIs5000() {
        #expect(TerminalProfile.default.scrollbackLineLimit == 5_000)
    }

    @Test func terminalProfileDefaultPaletteHas16Colors() {
        #expect(TerminalProfile.defaultPalette.count == 16)
    }
}

// MARK: - TerminalSessionTests
// Only lifecycle state is tested here; PTY I/O requires a real device
// and belongs in integration tests.

struct TerminalSessionTests {

    @Test func terminalSessionInitialStateIsIdle() async {
        let session = TerminalSession()
        let state = await session.state
        if case .idle = state { } else {
            Issue.record("Expected .idle initial state, got \(state)")
        }
    }

    @Test func terminalSessionSendThrowsWhenIdle() async {
        let session = TerminalSession()
        var didThrow = false
        do {
            try await session.send(Data("hello".utf8))
        } catch {
            didThrow = true
        }
        #expect(didThrow)
    }
}
