// TerminalModuleTests.swift
// Generated by !CreateTests skill — review before merging

import Testing
@testable import TerminalModule
import Foundation

// MARK: - TerminalOp extraction helpers
// TerminalOp is Sendable but not Equatable; these helpers let us assert on
// individual cases without manually pattern-matching in every test body.

extension TerminalOp {
    var printedChar: Character?               { if case .print(let c)  = self { return c };  return nil }
    var isBell: Bool                          { if case .bell           = self { return true }; return false }
    var isBackspace: Bool                     { if case .backspace      = self { return true }; return false }
    var isTab: Bool                           { if case .tab            = self { return true }; return false }
    var isNewline: Bool                       { if case .newline        = self { return true }; return false }
    var isCarriageReturn: Bool                { if case .carriageReturn = self { return true }; return false }
    var isSaveCursor: Bool                    { if case .saveCursor     = self { return true }; return false }
    var isRestoreCursor: Bool                 { if case .restoreCursor  = self { return true }; return false }
    var isEnterAltScreen: Bool                { if case .enterAltScreen = self { return true }; return false }
    var isExitAltScreen: Bool                 { if case .exitAltScreen  = self { return true }; return false }
    var sgrAttrs: [SGRAttribute]?             { if case .setAttributes(let a) = self { return a }; return nil }
    var eraseDisplayMode: EraseMode?          { if case .eraseDisplay(let m)  = self { return m }; return nil }
    var eraseLineMode: EraseMode?             { if case .eraseLine(let m)     = self { return m }; return nil }
    var moveCursorPos: (row: Int, col: Int)?  { if case .moveCursor(let r, let c) = self { return (r, c) }; return nil }
    var relDelta: (rows: Int, cols: Int)?     { if case .moveCursorRelative(let r, let c) = self { return (r, c) }; return nil }
    var setCursorColValue: Int?               { if case .setCursorCol(let c) = self { return c }; return nil }
    var setCursorRowValue: Int?               { if case .setCursorRow(let r) = self { return r }; return nil }
    var scrollUpCount: Int?                   { if case .scrollUp(let n)     = self { return n }; return nil }
    var titleValue: String?                   { if case .setTitle(let t)     = self { return t }; return nil }
    var cursorVisibility: Bool?               { if case .setCursorVisible(let v) = self { return v }; return nil }
}

// MARK: - Shared parse helpers

private func parse(_ string: String) -> [TerminalOp] {
    var p = ANSIParser()
    return p.parse(Data(string.utf8))
}

// MARK: - ANSIParserTests

struct ANSIParserTests {

    // MARK: Happy Path — ground-state control codes

    @Test func parserEmitsPrintForPrintableASCII() {
        let ops = parse("A")
        #expect(ops.first?.printedChar == "A")
    }

    @Test func parserEmitsBellFor0x07() {
        let ops = parse("\u{07}")
        #expect(ops.first?.isBell == true)
    }

    @Test func parserEmitsBackspaceFor0x08() {
        let ops = parse("\u{08}")
        #expect(ops.first?.isBackspace == true)
    }

    @Test func parserEmitsTabFor0x09() {
        let ops = parse("\u{09}")
        #expect(ops.first?.isTab == true)
    }

    @Test func parserEmitsNewlineForLF() {
        let ops = parse("\u{0A}")
        #expect(ops.first?.isNewline == true)
    }

    @Test func parserEmitsCarriageReturnFor0x0D() {
        let ops = parse("\u{0D}")
        #expect(ops.first?.isCarriageReturn == true)
    }

    // MARK: Happy Path — ESC sequences

    @Test func parserEmitsSaveCursorForESC7() {
        let ops = parse("\u{1B}7")
        #expect(ops.first?.isSaveCursor == true)
    }

    @Test func parserEmitsRestoreCursorForESC8() {
        let ops = parse("\u{1B}8")
        #expect(ops.first?.isRestoreCursor == true)
    }

    @Test func parserEmitsNewlineForESCD() {
        let ops = parse("\u{1B}D")  // IND
        #expect(ops.first?.isNewline == true)
    }

    @Test func parserEmitsScrollUp1ForESCM() {
        let ops = parse("\u{1B}M")  // RI
        #expect(ops.first?.scrollUpCount == 1)
    }

    // MARK: Happy Path — CSI cursor movement

    @Test func parserCUUMovesRelativelyUp() {
        let ops = parse("\u{1B}[3A")  // CUU 3
        #expect(ops.first?.relDelta?.rows == -3)
        #expect(ops.first?.relDelta?.cols == 0)
    }

    @Test func parserCUUDefaultsToOneRow() {
        let ops = parse("\u{1B}[A")  // CUU with no param
        #expect(ops.first?.relDelta?.rows == -1)
    }

    @Test func parserCUPPositionsCursorAbsolutely() {
        let ops = parse("\u{1B}[3;7H")  // CUP row=3 col=7 (1-based)
        #expect(ops.first?.moveCursorPos?.row == 2)
        #expect(ops.first?.moveCursorPos?.col == 6)
    }

    @Test func parserCUPWithNoParamsMovesToOrigin() {
        let ops = parse("\u{1B}[H")
        #expect(ops.first?.moveCursorPos?.row == 0)
        #expect(ops.first?.moveCursorPos?.col == 0)
    }

    @Test func parserCHASetsColumnZeroBased() {
        let ops = parse("\u{1B}[5G")  // CHA col=5 (1-based) → 4
        #expect(ops.first?.setCursorColValue == 4)
    }

    @Test func parserVPASetsRowZeroBased() {
        let ops = parse("\u{1B}[5d")  // VPA row=5 (1-based) → 4
        #expect(ops.first?.setCursorRowValue == 4)
    }

    // MARK: Happy Path — CSI erase

    @Test func parserEDWithNoParamErasesToEnd() {
        let ops = parse("\u{1B}[J")
        #expect(ops.first?.eraseDisplayMode == .toEnd)
    }

    @Test func parserEDParam1ErasesToStart() {
        let ops = parse("\u{1B}[1J")
        #expect(ops.first?.eraseDisplayMode == .toStart)
    }

    @Test func parserEDParam2ErasesAll() {
        let ops = parse("\u{1B}[2J")
        #expect(ops.first?.eraseDisplayMode == .all)
    }

    @Test func parserELParam2ErasesEntireLine() {
        let ops = parse("\u{1B}[2K")
        #expect(ops.first?.eraseLineMode == .all)
    }

    // MARK: Happy Path — CSI SGR attributes

    @Test func parserSGREmptyParamEmitsReset() {
        let ops = parse("\u{1B}[m")  // no param → reset
        #expect(ops.first?.sgrAttrs == [.reset])
    }

    @Test func parserSGR1EmitsBold() {
        let ops = parse("\u{1B}[1m")
        #expect(ops.first?.sgrAttrs == [.bold])
    }

    @Test func parserSGRForegroundANSIColor() {
        let ops = parse("\u{1B}[31m")  // red foreground
        #expect(ops.first?.sgrAttrs == [.foreground(.ansi(1))])
    }

    @Test func parserSGRBrightForeground() {
        let ops = parse("\u{1B}[91m")  // bright red foreground
        #expect(ops.first?.sgrAttrs == [.foreground(.ansi(9))])
    }

    @Test func parserSGR256ColorForeground() {
        let ops = parse("\u{1B}[38;5;200m")
        #expect(ops.first?.sgrAttrs == [.foreground(.palette(200))])
    }

    @Test func parserSGRTrueColorForeground() {
        let ops = parse("\u{1B}[38;2;255;128;0m")
        guard let attrs = ops.first?.sgrAttrs, let attr = attrs.first else {
            Issue.record("Expected one SGR attribute")
            return
        }
        if case .foreground(.rgb(let r, let g, let b)) = attr {
            #expect(r == 1.0)
            #expect(abs(g - 128.0 / 255.0) < 0.001)
            #expect(b == 0.0)
        } else {
            Issue.record("Expected .foreground(.rgb(...))")
        }
    }

    // MARK: Happy Path — DEC private modes

    @Test func parserHidesCursorViaDECPrivate25l() {
        let ops = parse("\u{1B}[?25l")
        #expect(ops.first?.cursorVisibility == false)
    }

    @Test func parserShowsCursorViaDECPrivate25h() {
        let ops = parse("\u{1B}[?25h")
        #expect(ops.first?.cursorVisibility == true)
    }

    @Test func parserEntersAltScreenVia1049h() {
        let ops = parse("\u{1B}[?1049h")
        #expect(ops.first?.isEnterAltScreen == true)
    }

    @Test func parserExitsAltScreenVia1049l() {
        let ops = parse("\u{1B}[?1049l")
        #expect(ops.first?.isExitAltScreen == true)
    }

    // MARK: Happy Path — OSC

    @Test func parserSetsTitleViaOSCBEL() {
        let ops = parse("\u{1B}]0;My Shell\u{07}")
        #expect(ops.first?.titleValue == "My Shell")
    }

    @Test func parserSetsTitleViaOSCStringTerminator() {
        // ESC ] 2 ; Hello ESC \
        let ops = parse("\u{1B}]2;Hello\u{1B}\\")
        #expect(ops.first?.titleValue == "Hello")
    }

    // MARK: Edge Cases

    @Test func parserReturnsEmptyOpsForEmptyInput() {
        let ops = parse("")
        #expect(ops.isEmpty)
    }

    @Test func parserDoesNotCrashOnTruncatedESC() {
        let ops = parse("\u{1B}")  // ESC with no following byte
        #expect(ops.isEmpty)
    }

    @Test func parserDoesNotCrashOnTruncatedCSI() {
        let ops = parse("\u{1B}[")  // ESC [ with no final byte
        #expect(ops.isEmpty)
    }

    @Test func parserIgnoresUnknownESCSequence() {
        let ops = parse("\u{1B}Z")  // ESC Z is not defined
        #expect(ops.isEmpty)
    }

    @Test func parserIgnoresUnknownCSIFinalByte() {
        let ops = parse("\u{1B}[99X")  // 0x58 = 'X', not handled
        #expect(ops.isEmpty)
    }

    @Test func parserSkipsC0ControlsBelow0x20() {
        // 0x01 (SOH) is not a known control — should produce no ops
        var p = ANSIParser()
        let ops = p.parse(Data([0x01]))
        #expect(ops.isEmpty)
    }

    @Test func parserScrollUpCSIUsesParam() {
        let ops = parse("\u{1B}[4S")
        #expect(ops.first?.scrollUpCount == 4)
    }
}

// MARK: - TerminalEmulatorTests

struct TerminalEmulatorTests {

    // MARK: Happy Path

    @Test func emulatorCursorStartsAtOrigin() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        let snap = await emu.snapshot()
        #expect(snap.cursorRow == 0)
        #expect(snap.cursorCol == 0)
    }

    @Test func emulatorCursorIsVisibleInitially() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        let snap = await emu.snapshot()
        #expect(snap.cursorVisible == true)
    }

    @Test func emulatorGridHasCorrectInitialDimensions() async {
        let emu = TerminalEmulator(cols: 10, rows: 5)
        let snap = await emu.snapshot()
        #expect(snap.grid.count == 5)
        #expect(snap.grid[0].count == 10)
    }

    @Test func emulatorPrintedCharacterAppearsInGrid() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("X".utf8))
        let snap = await emu.snapshot()
        #expect(snap.grid[0][0].character == "X")
    }

    @Test func emulatorCursorAdvancesAfterPrint() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("AB".utf8))
        let snap = await emu.snapshot()
        #expect(snap.cursorCol == 2)
    }

    @Test func emulatorNewlineAdvancesCursorRow() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("A\nB".utf8))
        let snap = await emu.snapshot()
        #expect(snap.cursorRow == 1)
    }

    @Test func emulatorCarriageReturnSetsCursorColToZero() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("HELLO\rX".utf8))
        let snap = await emu.snapshot()
        // X overwrote position 0 after carriage return
        #expect(snap.grid[0][0].character == "X")
    }

    @Test func emulatorBackspaceDecrementsCursorCol() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("AB\u{08}".utf8))  // print A, B, then backspace
        let snap = await emu.snapshot()
        #expect(snap.cursorCol == 1)
    }

    @Test func emulatorSetTitlePropagatesViaSnapshot() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("\u{1B}]0;TestTitle\u{07}".utf8))
        let snap = await emu.snapshot()
        #expect(snap.title == "TestTitle")
    }

    @Test func emulatorSetCursorInvisiblePropagatesViaSnapshot() async {
        let emu = TerminalEmulator(cols: 80, rows: 24)
        await emu.feed(Data("\u{1B}[?25l".utf8))
        let snap = await emu.snapshot()
        #expect(snap.cursorVisible == false)
    }

    @Test func emulatorScrollbackGrowsWhenScreenFills() async {
        let emu = TerminalEmulator(cols: 4, rows: 2)
        // CRLF resets cursor column; second CRLF pushes the first row into scrollback.
        await emu.feed(Data("AAAA\r\nBBBB\r\n".utf8))
        let snap = await emu.snapshot()
        #expect(snap.scrollback.count == 1)
    }

    @Test func emulatorResizePreservesExistingContent() async {
        let emu = TerminalEmulator(cols: 10, rows: 5)
        await emu.feed(Data("Hello".utf8))
        await emu.resize(cols: 20, rows: 10)
        let snap = await emu.snapshot()
        #expect(snap.grid[0][0].character == "H")
    }

    @Test func emulatorResizeClampsCursorToNewBounds() async {
        let emu = TerminalEmulator(cols: 10, rows: 10)
        await emu.feed(Data("\u{1B}[8;1H".utf8))  // CUP row=8, col=1 → (7, 0)
        await emu.resize(cols: 10, rows: 5)
        let snap = await emu.snapshot()
        #expect(snap.cursorRow <= 4)
    }

    @Test func emulatorResetClearsGridAndCursor() async {
        let emu = TerminalEmulator(cols: 10, rows: 5)
        await emu.feed(Data("ABC".utf8))
        await emu.reset()
        let snap = await emu.snapshot()
        #expect(snap.grid[0][0].character == " ")
        #expect(snap.cursorRow == 0)
        #expect(snap.cursorCol == 0)
    }

    @Test func emulatorAltScreenEnterClearsGrid() async {
        let emu = TerminalEmulator(cols: 10, rows: 5)
        await emu.feed(Data("HELLO".utf8))
        await emu.feed(Data("\u{1B}[?1049h".utf8))  // enter alt screen
        let snap = await emu.snapshot()
        #expect(snap.grid[0][0].character == " ")
    }

    @Test func emulatorAltScreenExitRestoresContent() async {
        let emu = TerminalEmulator(cols: 10, rows: 5)
        await emu.feed(Data("HELLO".utf8))
        await emu.feed(Data("\u{1B}[?1049h".utf8))  // enter alt screen
        await emu.feed(Data("WORLD".utf8))           // alt-screen content
        await emu.feed(Data("\u{1B}[?1049l".utf8))  // exit alt screen
        let snap = await emu.snapshot()
        #expect(snap.grid[0][0].character == "H")
    }
}

// MARK: - ScrollbackBufferTests

struct ScrollbackBufferTests {

    private func makeRow(_ char: Character, width: Int = 1) -> [ScreenCell] {
        [ScreenCell](repeating: ScreenCell(character: char), count: width)
    }

    // MARK: Happy Path

    @Test func scrollbackBufferStartsEmpty() {
        let buf = ScrollbackBuffer(capacity: 10)
        #expect(buf.lineCount == 0)
    }

    @Test func scrollbackBufferLinesIsEmptyInitially() {
        let buf = ScrollbackBuffer(capacity: 10)
        #expect(buf.lines().isEmpty)
    }

    @Test func scrollbackBufferLineCountGrowsOnAppend() {
        var buf = ScrollbackBuffer(capacity: 10)
        buf.append(makeRow("A"))
        buf.append(makeRow("B"))
        #expect(buf.lineCount == 2)
    }

    @Test func scrollbackBufferLinesReturnsInAppendOrder() {
        var buf = ScrollbackBuffer(capacity: 5)
        buf.append(makeRow("A"))
        buf.append(makeRow("B"))
        buf.append(makeRow("C"))
        let lines = buf.lines()
        #expect(lines[0].first?.character == "A")
        #expect(lines[1].first?.character == "B")
        #expect(lines[2].first?.character == "C")
    }

    @Test func scrollbackBufferCapacityIsRespected() {
        var buf = ScrollbackBuffer(capacity: 3)
        buf.append(makeRow("A"))
        buf.append(makeRow("B"))
        buf.append(makeRow("C"))
        buf.append(makeRow("D"))  // overflows — evicts A
        #expect(buf.lineCount == 3)
    }

    @Test func scrollbackBufferEvictsOldestLineOnOverflow() {
        var buf = ScrollbackBuffer(capacity: 3)
        buf.append(makeRow("A"))
        buf.append(makeRow("B"))
        buf.append(makeRow("C"))
        buf.append(makeRow("D"))  // evicts A
        let lines = buf.lines()
        #expect(lines.first?.first?.character == "B")
    }

    @Test func scrollbackBufferPreservesOldestToNewestOrderAfterWrap() {
        var buf = ScrollbackBuffer(capacity: 3)
        for ch: Character in ["A", "B", "C", "D"] { buf.append(makeRow(ch)) }
        let chars = buf.lines().compactMap { $0.first?.character }
        #expect(chars == ["B", "C", "D"])
    }

    @Test func scrollbackBufferClearResetsLineCount() {
        var buf = ScrollbackBuffer(capacity: 5)
        buf.append(makeRow("X"))
        buf.append(makeRow("Y"))
        buf.clear()
        #expect(buf.lineCount == 0)
    }

    @Test func scrollbackBufferClearMakesLinesEmpty() {
        var buf = ScrollbackBuffer(capacity: 5)
        buf.append(makeRow("X"))
        buf.clear()
        #expect(buf.lines().isEmpty)
    }

    // MARK: Edge Cases

    @Test func scrollbackBufferCapacityOneKeepsOnlyLastLine() {
        var buf = ScrollbackBuffer(capacity: 1)
        buf.append(makeRow("A"))
        buf.append(makeRow("B"))
        buf.append(makeRow("C"))
        let lines = buf.lines()
        #expect(lines.count == 1)
        #expect(lines.first?.first?.character == "C")
    }
}

// MARK: - KeyEncoderTests

private func makeKey(
    code: UInt16,
    chars: String,
    modifiers: TerminalModifiers = []
) -> TerminalKeyEvent {
    TerminalKeyEvent(keyCode: code, characters: chars, modifiers: modifiers)
}

struct KeyEncoderTests {

    // MARK: Happy Path — printable characters

    @Test func keyEncoderPassesThroughPrintableASCII() {
        let result = KeyEncoder.encode(makeKey(code: 0, chars: "a"))
        #expect(result == Data("a".utf8))
    }

    @Test func keyEncoderPassesThroughSpaceCharacter() {
        let result = KeyEncoder.encode(makeKey(code: 0, chars: " "))
        #expect(result == Data(" ".utf8))
    }

    // MARK: Happy Path — Ctrl combos

    @Test func keyEncoderCtrlCProduces0x03() {
        let result = KeyEncoder.encode(makeKey(code: 0, chars: "c", modifiers: .control))
        #expect(result == Data([0x03]))
    }

    @Test func keyEncoderCtrlAProduces0x01() {
        let result = KeyEncoder.encode(makeKey(code: 0, chars: "a", modifiers: .control))
        #expect(result == Data([0x01]))
    }

    @Test func keyEncoderCtrlZProduces0x1A() {
        let result = KeyEncoder.encode(makeKey(code: 0, chars: "z", modifiers: .control))
        #expect(result == Data([0x1A]))
    }

    // MARK: Happy Path — special keys

    @Test func keyEncoderReturnProducesCR() {
        let result = KeyEncoder.encode(makeKey(code: 36, chars: "\r"))
        #expect(result == Data([0x0D]))
    }

    @Test func keyEncoderTabProduces0x09() {
        let result = KeyEncoder.encode(makeKey(code: 48, chars: "\t"))
        #expect(result == Data([0x09]))
    }

    @Test func keyEncoderShiftTabProducesBackTabSequence() {
        let result = KeyEncoder.encode(makeKey(code: 48, chars: "\t", modifiers: .shift))
        #expect(result == Data([0x1B, 0x5B, 0x5A]))  // ESC [ Z
    }

    @Test func keyEncoderDeleteProduces0x7F() {
        let result = KeyEncoder.encode(makeKey(code: 51, chars: "\u{7F}"))
        #expect(result == Data([0x7F]))
    }

    @Test func keyEncoderEscapeProduces0x1B() {
        let result = KeyEncoder.encode(makeKey(code: 53, chars: "\u{1B}"))
        #expect(result == Data([0x1B]))
    }

    @Test func keyEncoderForwardDeleteProducesVT220Sequence() {
        let result = KeyEncoder.encode(makeKey(code: 117, chars: ""))
        #expect(result == Data([0x1B, 0x5B, 0x33, 0x7E]))  // ESC [ 3 ~
    }

    @Test func keyEncoderUpArrowProducesCursorUpSequence() {
        let result = KeyEncoder.encode(makeKey(code: 126, chars: ""))
        #expect(result == Data([0x1B, 0x5B, 0x41]))  // ESC [ A
    }

    @Test func keyEncoderShiftUpArrowProducesShiftedSequence() {
        let result = KeyEncoder.encode(makeKey(code: 126, chars: "", modifiers: .shift))
        // ESC [ 1 ; 2 A
        #expect(result == Data([0x1B, 0x5B, 0x31, 0x3B, 0x32, 0x41]))
    }

    @Test func keyEncoderLeftArrowProducesCursorBackSequence() {
        let result = KeyEncoder.encode(makeKey(code: 123, chars: ""))
        #expect(result == Data([0x1B, 0x5B, 0x44]))  // ESC [ D
    }

    @Test func keyEncoderHomeProducesCursorHomeSequence() {
        let result = KeyEncoder.encode(makeKey(code: 115, chars: ""))
        #expect(result == Data([0x1B, 0x5B, 0x48]))  // ESC [ H
    }

    @Test func keyEncoderOptionHomeProducesVT220HomeSequence() {
        let result = KeyEncoder.encode(makeKey(code: 115, chars: "", modifiers: .option))
        #expect(result == Data([0x1B, 0x5B, 0x31, 0x7E]))  // ESC [ 1 ~
    }

    @Test func keyEncoderPageUpProducesVT220PageUpSequence() {
        let result = KeyEncoder.encode(makeKey(code: 116, chars: ""))
        #expect(result == Data([0x1B, 0x5B, 0x35, 0x7E]))  // ESC [ 5 ~
    }

    // MARK: Error Conditions

    @Test func keyEncoderCommandKeyComboReturnsNil() {
        let result = KeyEncoder.encode(makeKey(code: 0, chars: "a", modifiers: .command))
        #expect(result == nil)
    }

    @Test func keyEncoderEmptyCharsWithNoSpecialKeyReturnsNil() {
        let result = KeyEncoder.encode(makeKey(code: 9999, chars: ""))
        #expect(result == nil)
    }
}

// MARK: - TerminalModifiersTests

struct TerminalModifiersTests {

    @Test func terminalModifiersControlFlagIsSet() {
        let mods = TerminalModifiers.control
        #expect(mods.contains(.control))
    }

    @Test func terminalModifiersCombinedContainsBothFlags() {
        let mods: TerminalModifiers = [.control, .shift]
        #expect(mods.contains(.shift))
    }

    @Test func terminalModifiersDoesNotContainUnrelatedFlag() {
        let mods = TerminalModifiers.control
        #expect(!mods.contains(.shift))
    }

    @Test func terminalModifiersEmptySetContainsNoFlag() {
        let mods: TerminalModifiers = []
        #expect(!mods.contains(.control))
    }
}

// MARK: - ScreenCellTests

struct ScreenCellTests {

    @Test func screenCellBlankHasSpaceCharacter() {
        #expect(ScreenCell.blank.character == " ")
    }

    @Test func screenCellDefaultInitMatchesBlank() {
        #expect(ScreenCell() == ScreenCell.blank)
    }

    @Test func screenCellCustomCharacterIsStored() {
        let cell = ScreenCell(character: "Z")
        #expect(cell.character == "Z")
    }

    @Test func screenCellForegroundColorIsStored() {
        let cell = ScreenCell(foreground: .ansi(2))
        #expect(cell.foreground == .ansi(2))
    }

    // MARK: CellStyle

    @Test func cellStylePlainHasAllFlagsFalse() {
        let style = CellStyle.plain
        #expect(!style.bold && !style.italic && !style.underline)
    }

    @Test func cellStyleMutationIsReflected() {
        var style = CellStyle.plain
        style.bold = true
        #expect(style.bold)
    }
}

// MARK: - TerminalProfileTests

struct TerminalProfileTests {

    @Test func terminalProfileDefaultFontNameIsMenlo() {
        #expect(TerminalProfile.default.fontName == "Menlo")
    }

    @Test func terminalProfileDefaultFontSizeIs13() {
        #expect(TerminalProfile.default.fontSize == 13.0)
    }

    @Test func terminalProfileDefaultScrollbackLimitIs5000() {
        #expect(TerminalProfile.default.scrollbackLineLimit == 5_000)
    }

    @Test func terminalProfileDefaultPaletteHas16Colors() {
        #expect(TerminalProfile.defaultPalette.count == 16)
    }
}

// MARK: - TerminalSessionTests
// Only lifecycle state is tested here; PTY I/O requires a real device
// and belongs in integration tests.

struct TerminalSessionTests {

    @Test func terminalSessionInitialStateIsIdle() async {
        let session = TerminalSession()
        let state = await session.state
        if case .idle = state { } else {
            Issue.record("Expected .idle initial state, got \(state)")
        }
    }

    @Test func terminalSessionSendThrowsWhenIdle() async {
        let session = TerminalSession()
        var didThrow = false
        do {
            try await session.send(Data("hello".utf8))
        } catch {
            didThrow = true
        }
        #expect(didThrow)
    }
}

// MARK: - TerminalSessionLifecycleTests
// Integration tests that launch a real /bin/zsh over a real PTY. They cover the
// EOF-driven stream teardown (ISS-070) and the SIGKILL escalation path (ISS-072)
// added in plan 7a. Each is bounded by a timeout so a regression hangs the test
// (and fails) rather than the whole suite.

private func withTimeout<T: Sendable>(
    seconds: Double,
    _ operation: @escaping @Sendable () async -> T
) async -> T? {
    await withTaskGroup(of: T?.self) { group in
        group.addTask { await operation() }
        group.addTask {
            try? await Task.sleep(nanoseconds: UInt64(seconds * 1_000_000_000))
            return nil
        }
        let result = await group.next() ?? nil
        group.cancelAll()
        return result
    }
}

struct TerminalSessionLifecycleTests {

    /// When the shell exits, the parent's slave copy is already closed, so the
    /// master sees EOF and the output stream finishes on its own (ISS-070). A
    /// regression (slave kept open) leaves the stream open and this times out.
    @Test func sessionStreamFinishesWhenShellExits() async throws {
        let session = TerminalSession()
        try await session.start()

        // Ask the shell to exit, then confirm the stream completes.
        try await session.send(Data("exit\n".utf8))

        let stream = await session.outputStream
        let finished = await withTimeout(seconds: 6) {
            for await _ in stream { }
            return true
        }
        #expect(finished == true)

        let state = await session.state
        if case .exited = state { } else if case .idle = state {
            Issue.record("Session unexpectedly idle after shell exit")
        } else if case .running = state {
            Issue.record("Session still running after shell exit")
        }
    }

    /// A shell that traps SIGTERM must still die: `terminate()` escalates to
    /// SIGKILL after its poll window (ISS-072). A regression (no escalation) hangs
    /// the shell and `terminate()` would block past the timeout.
    @Test func terminateEscalatesToKillForTrappingShell() async throws {
        let session = TerminalSession()
        try await session.start()

        // Ignore SIGTERM and block, so only SIGKILL can stop it.
        try await session.send(Data("trap '' TERM\nsleep 60\n".utf8))
        try? await Task.sleep(nanoseconds: 600_000_000)  // let the trap install

        let completed = await withTimeout(seconds: 6) {
            await session.terminate()
            return true
        }
        #expect(completed == true)

        // After teardown the channel is gone, so sends fail.
        var didThrow = false
        do { try await session.send(Data("x".utf8)) } catch { didThrow = true }
        #expect(didThrow)
    }

    /// `terminate()` is safe to call repeatedly and on an already-dead session.
    @Test func terminateIsIdempotent() async throws {
        let session = TerminalSession()
        try await session.start()
        let first = await withTimeout(seconds: 5) { await session.terminate(); return true }
        let second = await withTimeout(seconds: 5) { await session.terminate(); return true }
        #expect(first == true)
        #expect(second == true)
    }
}

// MARK: - PTYSpawn / controlling-terminal tests (plan 7b)
// These verify that the posix_spawn launch gives Zsh a controlling terminal so
// SIGINT (Ctrl-C) reaches the foreground process group (ISS-071) — the behaviour
// Foundation.Process could not provide.

/// Thread-safe accumulator for streamed shell output.
private actor OutputAccumulator {
    private var text = ""
    func append(_ chunk: String) { text += chunk }
    func contains(_ needle: String) -> Bool { text.contains(needle) }
}

struct PTYSpawnTests {

    @Test func exitCodeDecodesNormalExit() {
        // status 0 → exit 0; high byte holds the code for a normal exit.
        #expect(PTYSpawn.exitCode(fromWaitStatus: 0) == 0)
        #expect(PTYSpawn.exitCode(fromWaitStatus: 42 << 8) == 42)
    }

    @Test func exitCodeDecodesSignalTermination() {
        // Low 7 bits hold the terminating signal; convention is 128 + signal.
        #expect(PTYSpawn.exitCode(fromWaitStatus: SIGKILL) == 128 + SIGKILL)
    }

    /// Ctrl-C must interrupt a foreground `sleep` so the prompt returns and a
    /// follow-up command runs. The marker `DONE` only appears in the command's
    /// *output* — the echoed input line reads `echo DON''E`, which never contains
    /// the contiguous substring — so a match proves the echo actually executed.
    /// Without a controlling terminal the SIGINT is lost, `sleep 100` blocks, and
    /// this times out (ISS-071).
    @Test func ctrlCInterruptsForegroundCommand() async throws {
        let session = TerminalSession()
        try await session.start()
        let stream = await session.outputStream

        let accumulator = OutputAccumulator()
        let drain = Task {
            for await data in stream {
                if let text = String(data: data, encoding: .utf8) {
                    await accumulator.append(text)
                }
            }
        }
        defer { drain.cancel() }

        // Let the login shell finish loading before issuing commands.
        try? await Task.sleep(nanoseconds: 1_200_000_000)
        try await session.send(Data("sleep 100\n".utf8))
        try? await Task.sleep(nanoseconds: 800_000_000)   // let sleep reach the foreground
        try await session.send(Data([0x03]))              // Ctrl-C → SIGINT
        try await session.send(Data("echo DON''E\n".utf8))

        let interrupted = await withTimeout(seconds: 10) {
            while !Task.isCancelled {
                if await accumulator.contains("DONE") { return true }
                try? await Task.sleep(nanoseconds: 100_000_000)
            }
            return false
        }
        #expect(interrupted == true)

        await session.terminate()
    }
}

// MARK: - IncrementalLineDecoderTests (plan 7c, ISS-079)
// The observer line splitter must carry a partial multi-byte UTF-8 code point and a
// partial line across reads, so output split on arbitrary byte boundaries never drops
// characters or whole lines (the bug ISS-079 describes).

struct IncrementalLineDecoderTests {

    // MARK: incompleteTrailingByteCount

    @Test func decoderTreatsPureASCIIAsComplete() {
        let bytes = Array("hello".utf8)
        #expect(IncrementalLineDecoder.incompleteTrailingByteCount(bytes) == 0)
    }

    @Test func decoderHoldsLoneTwoByteLead() {
        // 0xC3 is the lead byte of 'é' (C3 A9); alone it is incomplete.
        #expect(IncrementalLineDecoder.incompleteTrailingByteCount([0xC3]) == 1)
    }

    @Test func decoderCompletesTwoByteSequence() {
        // Full 'é' — nothing to hold back.
        #expect(IncrementalLineDecoder.incompleteTrailingByteCount([0xC3, 0xA9]) == 0)
    }

    @Test func decoderHoldsPartialFourByteEmoji() {
        // '😀' is F0 9F 98 80; with only three of four bytes, hold all three.
        #expect(IncrementalLineDecoder.incompleteTrailingByteCount([0xF0, 0x9F, 0x98]) == 3)
    }

    @Test func decoderCompletesFourByteEmoji() {
        #expect(IncrementalLineDecoder.incompleteTrailingByteCount([0xF0, 0x9F, 0x98, 0x80]) == 0)
    }

    @Test func decoderHoldsOnlyTrailingPartialAfterCompleteCharacter() {
        // 'A' (complete) followed by a lone two-byte lead — hold just the last byte.
        #expect(IncrementalLineDecoder.incompleteTrailingByteCount([0x41, 0xC3]) == 1)
    }

    // MARK: feed / flush

    @Test func decoderEmitsLineOnNewline() {
        var decoder = IncrementalLineDecoder()
        let lines = decoder.feed(Data("hello\n".utf8))
        #expect(lines == ["hello"])
    }

    @Test func decoderHoldsLineUntilNewlineArrives() {
        var decoder = IncrementalLineDecoder()
        #expect(decoder.feed(Data("par".utf8)).isEmpty)
        let lines = decoder.feed(Data("tial\n".utf8))
        #expect(lines == ["partial"])
    }

    @Test func decoderReassemblesUTF8SplitAcrossReads() {
        // 'café\n' with the 'é' (C3 A9) split: first read ends mid-character.
        let full = Array("café\n".utf8)
        let splitAt = full.count - 2  // between C3 and A9
        var decoder = IncrementalLineDecoder()
        let first = decoder.feed(Data(full[0..<splitAt]))
        #expect(first.isEmpty)  // incomplete code point → no line yet
        let second = decoder.feed(Data(full[splitAt...]))
        #expect(second == ["café"])
    }

    @Test func decoderReassemblesEmojiSplitAcrossThreeReads() {
        let full = Array("hi 😀\n".utf8)  // emoji is 4 bytes
        var decoder = IncrementalLineDecoder()
        var out: [String] = []
        // Feed one byte at a time — the worst-case fragmentation.
        for byte in full { out += decoder.feed(Data([byte])) }
        #expect(out == ["hi 😀"])
    }

    @Test func decoderEmitsMultipleLinesInOneChunk() {
        var decoder = IncrementalLineDecoder()
        let lines = decoder.feed(Data("a\nb\nc\n".utf8))
        #expect(lines == ["a", "b", "c"])
    }

    @Test func decoderFlushReturnsTrailingPartialLine() {
        var decoder = IncrementalLineDecoder()
        _ = decoder.feed(Data("no newline".utf8))
        #expect(decoder.flush() == "no newline")
    }

    @Test func decoderFlushReturnsNilWhenNothingHeld() {
        var decoder = IncrementalLineDecoder()
        _ = decoder.feed(Data("line\n".utf8))
        #expect(decoder.flush() == nil)
    }

    @Test func decoderTrimsControlCharactersFromLines() {
        var decoder = IncrementalLineDecoder()
        // Carriage return before the newline should be trimmed off.
        let lines = decoder.feed(Data("text\r\n".utf8))
        #expect(lines == ["text"])
    }
}

// MARK: - ZDOTDIRShimTests (ISS-077)
// The shim is shell-script-in-a-string — the highest-risk surface. These pure tests
// pin the exact emitted scripts: that each file re-sources the user's real dotfile,
// re-points ZDOTDIR correctly, and that the OSC 133 hooks land ONLY in `.zshrc`
// (after the user's config, so a precmd_functions=(...) reset cannot drop them).

struct ZDOTDIRShimTests {

    @Test func eachShimSourcesItsRealCounterpart() {
        let c = ZDOTDIRShim.contents()
        #expect(c.zshenv.contains(#"source "$real/.zshenv""#))
        #expect(c.zprofile.contains(#"source "$real/.zprofile""#))
        #expect(c.zshrc.contains(#"source "$real/.zshrc""#))
        #expect(c.zlogin.contains(#"source "$real/.zlogin""#))
    }

    @Test func everyShimRestoresRealZDOTDIRBeforeSourcing() {
        // `real` is seeded from SPUTNIK_USER_ZDOTDIR (default $HOME) and ZDOTDIR is
        // set to it before the real file is sourced, so the user's config sees the
        // correct $ZDOTDIR.
        for body in [ZDOTDIRShim.contents().zshenv,
                     ZDOTDIRShim.contents().zprofile,
                     ZDOTDIRShim.contents().zshrc,
                     ZDOTDIRShim.contents().zlogin] {
            #expect(body.contains(#"local real="${SPUTNIK_USER_ZDOTDIR:-$HOME}""#))
            #expect(body.contains(#"ZDOTDIR="$real""#))
        }
    }

    @Test func nonTerminalShimsChainBackToShimDir() {
        // .zshenv and .zprofile must hand control back to the shim dir so the next
        // shim file still runs.
        let c = ZDOTDIRShim.contents()
        #expect(c.zshenv.contains("ZDOTDIR=\"${\(ZDOTDIRShim.shimDirVar):?"))
        #expect(c.zprofile.contains("ZDOTDIR=\"${\(ZDOTDIRShim.shimDirVar):?"))
    }

    @Test func terminalShimsRestoreUserZDOTDIRPermanently() {
        // .zshrc and .zlogin leave ZDOTDIR at the user's value for good.
        let c = ZDOTDIRShim.contents()
        #expect(c.zshrc.contains("ZDOTDIR=\"$\(ZDOTDIRShim.userZDOTDIRVar)\""))
        #expect(c.zlogin.contains("ZDOTDIR=\"$\(ZDOTDIRShim.userZDOTDIRVar)\""))
        // ...and they do NOT chain back to the shim dir.
        #expect(!c.zshrc.contains(ZDOTDIRShim.shimDirVar))
        #expect(!c.zlogin.contains(ZDOTDIRShim.shimDirVar))
    }

    @Test func everyShimRecapturesUserRelocatedZDOTDIR() {
        // After sourcing, a user file may have reset ZDOTDIR; the shim re-captures it
        // so the relocation is honoured for later files (and the final value).
        for body in [ZDOTDIRShim.contents().zshenv,
                     ZDOTDIRShim.contents().zprofile,
                     ZDOTDIRShim.contents().zshrc,
                     ZDOTDIRShim.contents().zlogin] {
            #expect(body.contains(#"SPUTNIK_USER_ZDOTDIR="${ZDOTDIR:-$real}""#))
        }
    }

    @Test func osc133HooksAppearOnlyInZshrc() {
        let c = ZDOTDIRShim.contents()
        #expect(c.zshrc.contains("precmd_functions+=(__sputnik_precmd)"))
        #expect(c.zshrc.contains("preexec_functions+=(__sputnik_preexec)"))
        #expect(!c.zshenv.contains("__sputnik_precmd"))
        #expect(!c.zprofile.contains("__sputnik_precmd"))
        #expect(!c.zlogin.contains("__sputnik_precmd"))
    }

    @Test func hooksAreAppendedAfterTheUserConfigSource() {
        // The append must come AFTER `source "$real/.zshrc"` so a wholesale
        // precmd_functions=(...) reset in the user's config cannot drop our hook.
        let body = ZDOTDIRShim.contents().zshrc
        guard let sourceRange = body.range(of: #"source "$real/.zshrc""#),
              let hookRange = body.range(of: "precmd_functions+=(__sputnik_precmd)") else {
            Issue.record("Expected both the source line and the hook append in .zshrc")
            return
        }
        #expect(sourceRange.lowerBound < hookRange.lowerBound)
    }

    @Test func hooksEmitTheFourOSC133Markers() {
        // The literal escape/bell bytes must be present so the emitted printf writes
        // real OSC 133 sequences (A/B/C/D).
        let hooks = ZDOTDIRShim.osc133Hooks
        #expect(hooks.contains(#"\033]133;A\007"#))
        #expect(hooks.contains(#"\033]133;B\007"#))
        #expect(hooks.contains(#"\033]133;C\007"#))
        #expect(hooks.contains(#"\033]133;D;%s\007"#))
    }

    @Test func installWritesAllFourFilesWithRestrictivePermissions() throws {
        let dir = try ZDOTDIRShim.install()
        defer { try? FileManager.default.removeItem(at: dir) }

        for name in [".zshenv", ".zprofile", ".zshrc", ".zlogin"] {
            let url = dir.appendingPathComponent(name)
            #expect(FileManager.default.fileExists(atPath: url.path))
            let perms = try FileManager.default.attributesOfItem(atPath: url.path)[.posixPermissions] as? NSNumber
            #expect(perms?.int16Value == 0o600)
        }
        let dirPerms = try FileManager.default.attributesOfItem(atPath: dir.path)[.posixPermissions] as? NSNumber
        #expect(dirPerms?.int16Value == 0o700)
    }
}

// MARK: - ZDOTDIRShim integration (ISS-077)
// Spawns a real `zsh --login` over a real PTY with the shim wired in, using a fixture
// "home" whose .zshrc both defines an alias AND clobbers precmd_functions wholesale —
// the exact failure the old timed stdin injection could not survive. Proves the user's
// config loads (alias works) and the OSC 133 prompt marker still appears.

struct ZDOTDIRShimIntegrationTests {

    @Test func shimLoadsUserConfigAndInstallsHooksDespiteClobber() async throws {
        let fixture = FileManager.default.temporaryDirectory
            .appendingPathComponent("sputnik-shim-fixture-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: fixture, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: fixture) }

        let zshrc = """
            alias sputnik_marker='echo MARKER_OK'
            precmd_functions=()
            preexec_functions=()
            """
        try Data((zshrc + "\n").utf8).write(to: fixture.appendingPathComponent(".zshrc"))

        let shimDir = try ZDOTDIRShim.install()
        defer { try? FileManager.default.removeItem(at: shimDir) }

        var env = ProcessInfo.processInfo.environment
        env["TERM"] = "xterm-256color"
        env["ZDOTDIR"] = shimDir.path
        env[ZDOTDIRShim.shimDirVar] = shimDir.path
        env[ZDOTDIRShim.userZDOTDIRVar] = fixture.path

        let launched = try PTYSpawn.spawnLoginShell(
            executable: "/bin/zsh", arguments: ["--login"],
            workingDirectory: fixture.path, environment: env)
        let fd = launched.masterFD
        defer {
            kill(launched.pid, SIGKILL)
            var status: Int32 = 0
            waitpid(launched.pid, &status, 0)
            close(fd)
        }

        let accumulator = OutputAccumulator()
        let drain = Task.detached {
            var buffer = [UInt8](repeating: 0, count: 4096)
            while !Task.isCancelled {
                let n = read(fd, &buffer, buffer.count)
                if n <= 0 { break }
                if let text = String(bytes: buffer[0..<n], encoding: .utf8) {
                    await accumulator.append(text)
                }
            }
        }
        defer { drain.cancel() }

        // Let the login shell finish loading, then trigger a command + a fresh prompt.
        try? await Task.sleep(nanoseconds: 1_500_000_000)
        _ = "sputnik_marker\n".withCString { write(fd, $0, strlen($0)) }

        let ok = await withTimeout(seconds: 10) {
            while !Task.isCancelled {
                // MARKER_OK → the user's alias loaded (real .zshrc sourced);
                // ESC]133;A → the precmd hook fired despite the wholesale clobber.
                if await accumulator.contains("MARKER_OK"),
                   await accumulator.contains("\u{1b}]133;A") { return true }
                try? await Task.sleep(nanoseconds: 100_000_000)
            }
            return false
        }
        #expect(ok == true)
    }
}
