// HTMLPreviewModuleTests.swift
// Generated by !CreateTests skill — review before merging

import Testing
@testable import HTMLPreviewModule
import Foundation

// MARK: - Decision helpers
// Decision is Sendable but not Equatable; these properties avoid pattern-matching
// in every assertion.

extension LinkNavigationPolicy.Decision {
    var isAllowInPage: Bool {
        if case .allowInPage = self { return true }
        return false
    }
    var openAsTabURL: URL? {
        if case .openAsTab(let url) = self { return url }
        return nil
    }
    var openExternallyURL: URL? {
        if case .openExternally(let url) = self { return url }
        return nil
    }
    var isBlock: Bool {
        if case .block = self { return true }
        return false
    }
}

// MARK: - LinkNavigationPolicyTests

struct LinkNavigationPolicyTests {

    // MARK: Happy Path

    @Test func httpURLOpenedExternally() {
        let url = URL(string: "http://example.com")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.openExternallyURL == url)
    }

    @Test func httpsURLOpenedExternally() {
        let url = URL(string: "https://example.com/page")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.openExternallyURL == url)
    }

    @Test func localFileURLOpenedAsTab() {
        let base = URL(string: "file:///Users/test/site/")!
        let url = URL(string: "file:///Users/test/site/page.html")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: base)
        #expect(d.openAsTabURL == url)
    }

    @Test func mailtoURLOpenedExternally() {
        let url = URL(string: "mailto:user@example.com")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.openExternallyURL == url)
    }

    @Test func inPageAnchorAllowedInPage() {
        // currentBaseURL is the document's parent directory (set from deletingLastPathComponent).
        // Fragment links in the loaded page resolve against the baseURL directory.
        let base = URL(string: "file:///Users/test/site/")!
        let anchor = URL(string: "file:///Users/test/site/#section-2")!
        let d = LinkNavigationPolicy.decide(for: anchor, targetIsBlank: false, currentBaseURL: base)
        #expect(d.isAllowInPage)
    }

    @Test func markdownFileOpenedAsTab() {
        let base = URL(string: "file:///Users/test/site/")!
        let url = URL(string: "file:///Users/test/site/readme.md")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: base)
        #expect(d.openAsTabURL == url)
    }

    @Test func pdfFileOpenedAsTab() {
        let base = URL(string: "file:///Users/test/site/")!
        let url = URL(string: "file:///Users/test/site/doc.pdf")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: base)
        #expect(d.openAsTabURL == url)
    }

    // MARK: Edge Cases

    @Test func targetBlankForFileURLOpenedExternally() {
        // target="_blank" takes priority — file URL is opened in browser, not as a tab.
        let base = URL(string: "file:///Users/test/site/")!
        let url = URL(string: "file:///Users/test/site/page.html")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: true, currentBaseURL: base)
        #expect(d.openExternallyURL == url)
    }

    @Test func targetBlankForHttpsURLOpenedExternally() {
        let url = URL(string: "https://example.com")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: true, currentBaseURL: nil)
        #expect(d.openExternallyURL == url)
    }

    @Test func anchorOnDifferentFileIsNotInPage() {
        let base = URL(string: "file:///Users/test/site/")!
        // Fragment pointing at a DIFFERENT file — should open as tab, not scroll in place.
        let other = URL(string: "file:///Users/test/site/other.html#section")!
        let d = LinkNavigationPolicy.decide(for: other, targetIsBlank: false, currentBaseURL: base)
        #expect(!d.isAllowInPage)
        #expect(d.openAsTabURL == other)
    }

    @Test func httpsWithFragmentOpenedExternally() {
        // External URLs with fragments are still external — not in-page.
        let url = URL(string: "https://example.com/page#top")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.openExternallyURL == url)
    }

    @Test func fileURLWithNilBaseOpenedAsTab() {
        // No base URL provided — any file:// link opens as a new tab.
        let url = URL(string: "file:///Users/test/other.html")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.openAsTabURL == url)
    }

    @Test func httpURLWithPathAndQueryOpenedExternally() {
        let url = URL(string: "https://example.com/a/b?q=1&page=2")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.openExternallyURL != nil)
    }

    @Test func mailtoWithAddressAndSubjectOpenedExternally() {
        let url = URL(string: "mailto:admin@example.com")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.openExternallyURL == url)
    }

    @Test func inPageAnchorWithDifferentBaseIsNotAllowInPage() {
        let base = URL(string: "file:///Users/test/a.html")!
        let anchor = URL(string: "file:///Users/test/b.html#section")!
        let d = LinkNavigationPolicy.decide(for: anchor, targetIsBlank: false, currentBaseURL: base)
        #expect(!d.isAllowInPage)
    }

    // MARK: Error Conditions

    @Test func javascriptSchemeBlocked() {
        let url = URL(string: "javascript:foo")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.isBlock)
    }

    @Test func dataSchemeBlocked() {
        let url = URL(string: "data:text/plain,hello")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.isBlock)
    }

    @Test func blobSchemeBlocked() {
        let url = URL(string: "blob:some-uuid-1234")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.isBlock)
    }

    @Test func ftpSchemeBlocked() {
        let url = URL(string: "ftp://files.example.com/file.txt")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.isBlock)
    }

    @Test func unknownCustomSchemeBlocked() {
        let url = URL(string: "myapp://open/document")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.isBlock)
    }

    @Test func relativePathWithNoSchemeBlocked() {
        // A URL that failed full resolution and has no scheme is blocked.
        guard let url = URL(string: "relative/path.html") else { return }
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.isBlock)
    }

    @Test func sputnikImageSchemeBlocked() {
        // The internal sputnik-img:// scheme used for image rewriting must not
        // navigate the page if clicked somehow.
        let url = URL(string: "sputnik-img://host/photo.png")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: false, currentBaseURL: nil)
        #expect(d.isBlock)
    }

    @Test func targetBlankDoesNotOverrideJavascriptScheme() {
        // javascript: must always block — target=_blank must not route it to
        // NSWorkspace.open(), which would be called on a harmful URL.
        let url = URL(string: "javascript:foo")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: true, currentBaseURL: nil)
        #expect(d.isBlock)
    }

    @Test func targetBlankDoesNotOverrideDataScheme() {
        // data: must always block regardless of target=_blank.
        let url = URL(string: "data:text/plain,hello")!
        let d = LinkNavigationPolicy.decide(for: url, targetIsBlank: true, currentBaseURL: nil)
        #expect(d.isBlock)
    }
}

// MARK: - HTMLPreviewCoordinatorTests

@MainActor
struct HTMLPreviewCoordinatorTests {

    // MARK: Happy Path

    @Test func initialCapturedSelectionIsEmpty() {
        let c = HTMLPreviewCoordinator(router: nil)
        #expect(c.capturedSelection.isEmpty)
    }

    @Test func initialLinkNavigationIsEnabled() {
        let c = HTMLPreviewCoordinator(router: nil)
        #expect(c.isLinkNavigationEnabled == true)
    }

    @Test func initialCurrentBaseURLIsNil() {
        let c = HTMLPreviewCoordinator(router: nil)
        #expect(c.currentBaseURL == nil)
    }

    @Test func initialFullSessionTextIsEmpty() {
        let c = HTMLPreviewCoordinator(router: nil)
        #expect(c.fullSessionText.isEmpty)
    }

    // MARK: State Transitions

    @Test func capturedSelectionCanBeUpdated() {
        let c = HTMLPreviewCoordinator(router: nil)
        c.capturedSelection = "hello world"
        #expect(c.capturedSelection == "hello world")
    }

    @Test func capturedSelectionCanBeCleared() {
        let c = HTMLPreviewCoordinator(router: nil)
        c.capturedSelection = "some text"
        c.capturedSelection = ""
        #expect(c.capturedSelection.isEmpty)
    }

    @Test func linkNavigationCanBeDisabled() {
        let c = HTMLPreviewCoordinator(router: nil)
        c.isLinkNavigationEnabled = false
        #expect(c.isLinkNavigationEnabled == false)
    }

    @Test func currentBaseURLCanBeSet() {
        let c = HTMLPreviewCoordinator(router: nil)
        let url = URL(string: "file:///Users/test/site/")!
        c.currentBaseURL = url
        #expect(c.currentBaseURL == url)
    }

    @Test func currentBaseURLCanBeCleared() {
        let c = HTMLPreviewCoordinator(router: nil)
        c.currentBaseURL = URL(string: "file:///Users/test/")!
        c.currentBaseURL = nil
        #expect(c.currentBaseURL == nil)
    }

    @Test func fullSessionTextCanBeSet() {
        let c = HTMLPreviewCoordinator(router: nil)
        c.fullSessionText = "<html><body>Hello</body></html>"
        #expect(c.fullSessionText == "<html><body>Hello</body></html>")
    }

    @Test func onLoadErrorCallbackIsInvoked() {
        let c = HTMLPreviewCoordinator(router: nil)
        var received: String?
        c.onLoadError = { received = $0 }
        c.onLoadError?("connection refused")
        #expect(received == "connection refused")
    }

    @Test func isShowingPlaceholderDefaultsToFalse() {
        let c = HTMLPreviewCoordinator(router: nil)
        #expect(c.isShowingPlaceholder == false)
    }
}

// MARK: - splitHTML

@MainActor
struct SplitHTMLTests {

    /// ISS-086: a closed-range subscript trapped when `</head>` ended the string.
    /// The half-open form must split head-only HTML without crashing.
    @Test func headOnlyHTMLDoesNotCrash() {
        let (head, body) = HTMLPreviewCoordinator.splitHTML("<html><head></head>")
        #expect(head == "<html><head></head>")
        #expect(body.isEmpty)
    }

    @Test func headAndEmptyBodySplitsCorrectly() {
        let (head, body) = HTMLPreviewCoordinator.splitHTML("<html><head></head><body></body>")
        #expect(head == "<html><head></head>")
        #expect(body.isEmpty)
    }

    @Test func headAndBodyContentSplitsCorrectly() {
        let (head, body) = HTMLPreviewCoordinator.splitHTML(
            "<html><head><title>x</title></head><body><p>hi</p></body></html>")
        #expect(head == "<html><head><title>x</title></head>")
        #expect(body == "<p>hi</p>")
    }

    @Test func noHeadReturnsWholeStringAsBody() {
        let (head, body) = HTMLPreviewCoordinator.splitHTML("<p>no head here</p>")
        #expect(head.isEmpty)
        #expect(body == "<p>no head here</p>")
    }
}
