// TextEditorModuleTests.swift
// Generated by !CreateTests skill — review before merging

import AppKit
import Foundation
import FoundationModule
import Testing

@testable import TextEditorModule

// MARK: - Test helpers

/// Minimal mock persistence service that does nothing — sufficient for EditorViewModel
/// tests that don't exercise crash recovery persistence paths.
@MainActor
private final class MockPersistenceService: PersistenceService {
    func restore() async -> LayoutState { .default }
    func flushLayout(_: LayoutState) {}
    func flushLayoutSync(_: LayoutState) {}
    func restoreWindows() async -> [WindowDescriptor] { [] }
    func saveWindows(_: [WindowDescriptor]) {}
    func saveWindowsSync(_: [WindowDescriptor]) {}
    func writeRecovery(for: URL, content: String) {}
    func clearRecovery(for: URL) {}
    func pendingRecoveryNames() -> [String] { [] }
    func saveSetting<T: Encodable>(_: T, forKey: String) {}
    func loadSetting<T: Decodable>(forKey: String) -> T? { nil }
    func saveScratchpad(text: String) {}
    func loadScratchpadText() -> String { "" }
    func saveScratchpadDockedWidth(_: CGFloat) {}
    func loadScratchpadDockedWidth() -> CGFloat { 280 }
}

/// Creates an `EditorViewModel` with test defaults (a fresh `AppState` and
/// `MockPersistenceService`), avoiding the old `NSApp.delegate` lookup (ISS-056).
@MainActor
private func makeTestEditorViewModel() -> EditorViewModel {
    EditorViewModel(appState: AppState(), persistenceService: MockPersistenceService())
}

private func writeTempFile(content: String, name: String) throws -> URL {
    let url = FileManager.default.temporaryDirectory.appendingPathComponent(name)
    try content.write(to: url, atomically: true, encoding: .utf8)
    return url
}

@MainActor
private func makeSolidImage(color: NSColor, size: CGSize) -> NSImage {
    let image = NSImage(size: size)
    image.lockFocus()
    color.setFill()
    NSRect(origin: .zero, size: size).fill()
    image.unlockFocus()
    return image
}

// MARK: - EditorModeTests

struct EditorModeTests {

    // MARK: Happy Path

    @Test func allCasesCount() {
        #expect(EditorMode.allCases.count == 4)
    }

    @Test func plainTextRawValue() {
        #expect(EditorMode.plainText.rawValue == "Plain Text")
    }

    @Test func markdownRawValue() {
        #expect(EditorMode.markdown.rawValue == "Markdown")
    }

    @Test func htmlRawValue() {
        #expect(EditorMode.html.rawValue == "HTML")
    }

    @Test func asciiArtRawValue() {
        #expect(EditorMode.asciiArt.rawValue == "ASCII Art")
    }

    // MARK: Edge Cases

    @Test func initFromValidRawValue() {
        #expect(EditorMode(rawValue: "Markdown") == .markdown)
    }

    @Test func initFromInvalidRawValueReturnsNil() {
        #expect(EditorMode(rawValue: "invalid") == nil)
    }
}

// MARK: - EncodingGuardTests

struct EncodingGuardTests {

    // MARK: Happy Path

    @Test func defaultMaxBytesIsTenMegabytes() {
        #expect(EncodingGuard.defaultMaxBytes == 10 * 1024 * 1024)
    }

    @Test func validUTF8FileReturnsUTF8() throws {
        let url = try writeTempFile(content: "Hello, world!", name: "eg_utf8.txt")
        defer { try? FileManager.default.removeItem(at: url) }
        let enc = try EncodingGuard.validate(url)
        #expect(enc == .utf8)
    }

    @Test func emptyFileReturnsUTF8() throws {
        let url = try writeTempFile(content: "", name: "eg_empty.txt")
        defer { try? FileManager.default.removeItem(at: url) }
        let enc = try EncodingGuard.validate(url)
        #expect(enc == .utf8)
    }

    @Test func fileSizeAtExactLimitSucceeds() throws {
        let content = String(repeating: "x", count: 50)
        let url = try writeTempFile(content: content, name: "eg_exact.txt")
        defer { try? FileManager.default.removeItem(at: url) }
        let enc = try EncodingGuard.validate(url, maxBytes: 50)
        #expect(enc == .utf8)
    }

    // MARK: Edge Cases

    @Test func lowNullRatioPassesBinaryCheck() throws {
        // 1 null in ~14 bytes ≈ 7% — below the 15% rejection threshold.
        var data = Data("Hello, world!".utf8)
        data.append(0x00)
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("eg_lownull.txt")
        try data.write(to: url)
        defer { try? FileManager.default.removeItem(at: url) }
        let enc = try EncodingGuard.validate(url)
        #expect(enc == .utf8)
    }

    @Test func fileSizeOneByteOverLimitThrows() throws {
        let url = try writeTempFile(content: String(repeating: "x", count: 51), name: "eg_over.txt")
        defer { try? FileManager.default.removeItem(at: url) }
        #expect(throws: EncodingGuard.Failure.self) {
            try EncodingGuard.validate(url, maxBytes: 50)
        }
    }

    // MARK: Error Conditions

    @Test func oversizedFileThrowsFileTooLarge() throws {
        let url = try writeTempFile(content: String(repeating: "a", count: 100), name: "eg_big.txt")
        defer { try? FileManager.default.removeItem(at: url) }
        #expect(throws: EncodingGuard.Failure.self) {
            try EncodingGuard.validate(url, maxBytes: 10)
        }
    }

    @Test func binaryDataThrowsBinaryOrUnreadable() throws {
        let nullBytes = Data(repeating: 0x00, count: 200)
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("eg_binary.bin")
        try nullBytes.write(to: url)
        defer { try? FileManager.default.removeItem(at: url) }
        #expect(throws: EncodingGuard.Failure.self) {
            try EncodingGuard.validate(url)
        }
    }

    @Test func fileTooLargeErrorCarriesCorrectURL() throws {
        let url = try writeTempFile(content: "abc", name: "eg_urlcheck.txt")
        defer { try? FileManager.default.removeItem(at: url) }
        do {
            _ = try EncodingGuard.validate(url, maxBytes: 1)
            Issue.record("Expected EncodingGuard.Failure.fileTooLarge to be thrown")
        } catch EncodingGuard.Failure.fileTooLarge(let errURL, _, _) {
            #expect(errURL.lastPathComponent == url.lastPathComponent)
        } catch {
            Issue.record("Unexpected error type: \(error)")
        }
    }
}

// MARK: - GrammarAnnotationTests

struct GrammarAnnotationTests {

    // MARK: Happy Path

    @Test func spellingAnnotationKind() {
        let ann = GrammarAnnotation(
            range: NSRange(location: 0, length: 5), kind: .spelling, suggestions: ["fix"])
        #expect(ann.kind == .spelling)
    }

    @Test func grammarAnnotationSuggestions() {
        let ann = GrammarAnnotation(
            range: NSRange(location: 3, length: 2), kind: .grammar, suggestions: ["a", "b"])
        #expect(ann.suggestions == ["a", "b"])
    }

    @Test func isSuppressedDefaultsFalse() {
        let ann = GrammarAnnotation(
            range: NSRange(location: 0, length: 1), kind: .spelling, suggestions: [])
        #expect(!ann.isSuppressed)
    }

    @Test func suppressedFlagRoundtrips() {
        let ann = GrammarAnnotation(
            range: NSRange(location: 0, length: 1), kind: .grammar, suggestions: [],
            isSuppressed: true)
        #expect(ann.isSuppressed)
    }

    // MARK: Edge Cases

    @Test func equalAnnotationsAreEqual() {
        let a = GrammarAnnotation(
            range: NSRange(location: 2, length: 4), kind: .spelling, suggestions: ["ok"])
        let b = GrammarAnnotation(
            range: NSRange(location: 2, length: 4), kind: .spelling, suggestions: ["ok"])
        #expect(a == b)
    }

    @Test func differentRangeMakesAnnotationsUnequal() {
        let a = GrammarAnnotation(
            range: NSRange(location: 0, length: 3), kind: .spelling, suggestions: [])
        let b = GrammarAnnotation(
            range: NSRange(location: 1, length: 3), kind: .spelling, suggestions: [])
        #expect(a != b)
    }
}

// MARK: - SpellCheckFileTypeGuardTests

@MainActor
struct SpellCheckFileTypeGuardTests {

    // MARK: Happy Path

    @Test func txtFileActivatesSpellCheck() {
        let vm = makeTestEditorViewModel()
        SpellCheckFileTypeGuard.check(URL(fileURLWithPath: "/tmp/notes.txt"), viewModel: vm)
        #expect(vm.spellCheckActive)
    }

    @Test func mdFileActivatesSpellCheck() {
        let vm = makeTestEditorViewModel()
        SpellCheckFileTypeGuard.check(URL(fileURLWithPath: "/tmp/readme.md"), viewModel: vm)
        #expect(vm.spellCheckActive)
    }

    // MARK: Error Conditions

    @Test func htmlFileDoesNotActivateSpellCheck() {
        let vm = makeTestEditorViewModel()
        SpellCheckFileTypeGuard.check(URL(fileURLWithPath: "/tmp/index.html"), viewModel: vm)
        #expect(!vm.spellCheckActive)
    }

    @Test func binaryFileDoesNotActivateSpellCheck() {
        let vm = makeTestEditorViewModel()
        SpellCheckFileTypeGuard.check(URL(fileURLWithPath: "/tmp/archive.zip"), viewModel: vm)
        #expect(!vm.spellCheckActive)
    }

    // MARK: Edge Cases

    @Test func uppercaseExtensionIsNormalized() {
        let vm = makeTestEditorViewModel()
        SpellCheckFileTypeGuard.check(URL(fileURLWithPath: "/tmp/Notes.MD"), viewModel: vm)
        #expect(vm.spellCheckActive)
    }
}

// MARK: - HTMLDocTypeGuardTests

@MainActor
struct HTMLDocTypeGuardTests {

    // MARK: Happy Path

    @Test func lowercaseDoctypeActivatesHTMLMode() {
        let vm = makeTestEditorViewModel()
        HTMLDocTypeGuard.check("<!doctype html><html>", viewModel: vm)
        #expect(vm.htmlModeActive)
    }

    @Test func mixedCaseDoctypeActivatesHTMLMode() {
        let vm = makeTestEditorViewModel()
        HTMLDocTypeGuard.check("<!DOCTYPE HTML>\n<html>", viewModel: vm)
        #expect(vm.htmlModeActive)
    }

    // MARK: Error Conditions

    @Test func missingDoctypeDoesNotActivate() {
        let vm = makeTestEditorViewModel()
        HTMLDocTypeGuard.check("<html><body>No doctype</body></html>", viewModel: vm)
        #expect(!vm.htmlModeActive)
    }

    @Test func emptyContentDoesNotActivate() {
        let vm = makeTestEditorViewModel()
        HTMLDocTypeGuard.check("", viewModel: vm)
        #expect(!vm.htmlModeActive)
    }

    // MARK: Edge Cases

    @Test func doctypeBeyond512CharsIsNotDetected() {
        let vm = makeTestEditorViewModel()
        let padding = String(repeating: "x", count: 520)
        HTMLDocTypeGuard.check(padding + "<!doctype html>", viewModel: vm)
        #expect(!vm.htmlModeActive)
    }
}

// MARK: - HTMLLanguageProviderTests

@MainActor
struct HTMLLanguageProviderTests {

    // MARK: Happy Path

    @Test func openTagSuggestsMatchingCloseTag() {
        let result = HTMLLanguageProvider.suggest(in: "<div", cursorPos: 4)
        #expect(result == ">\n</div>")
    }

    @Test func attributeEqualsQuoteGetsClosed() {
        let result = HTMLLanguageProvider.suggest(in: "<p class=\"", cursorPos: 10)
        #expect(result == "\"")
    }

    @Test func headingTagSuggestsClose() {
        let result = HTMLLanguageProvider.suggest(in: "<h2", cursorPos: 3)
        #expect(result == ">\n</h2>")
    }

    @Test func voidElementWithSpaceSuggestsSelfClose() {
        // The generic `<tagname` regex fires first for bare `<img`.
        // Adding a space breaks the generic regex, letting the void-element check fire.
        let result = HTMLLanguageProvider.suggest(in: "<img ", cursorPos: 5)
        #expect(result == " />")
    }

    // MARK: Edge Cases

    @Test func plaintextReturnsNil() {
        let result = HTMLLanguageProvider.suggest(in: "Hello world", cursorPos: 11)
        #expect(result == nil)
    }

    @Test func emptyStringReturnsNil() {
        let result = HTMLLanguageProvider.suggest(in: "", cursorPos: 0)
        #expect(result == nil)
    }

    // MARK: Error Conditions

    @Test func cursorPastEndOfStringDoesNotCrash() {
        let result = HTMLLanguageProvider.suggest(in: "abc", cursorPos: 999)
        #expect(result == nil)
    }
}

// MARK: - BlockCompletionTests

@MainActor
struct BlockCompletionTests {

    // MARK: Happy Path

    @Test func applyInsertsFrameReplacingPattern() {
        let bc = BlockCompletion()
        bc.stage(
            BlockCompletion.Payload(pattern: "+--", frame: "+---+\n|   |\n+---+", preview: "+---+"))
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "+--"))
        tv.setSelectedRange(NSRange(location: 3, length: 0))
        bc.apply(to: tv)
        #expect(tv.textStorage?.string == "+---+\n|   |\n+---+")
    }

    @Test func discardPreventsApply() {
        let bc = BlockCompletion()
        bc.stage(BlockCompletion.Payload(pattern: "+--", frame: "FRAME", preview: "preview"))
        bc.discard()
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "+--"))
        tv.setSelectedRange(NSRange(location: 3, length: 0))
        bc.apply(to: tv)
        #expect(tv.textStorage?.string == "+--")
    }

    @Test func applyWithNoStagedPayloadIsNoOp() {
        let bc = BlockCompletion()
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "hello"))
        tv.setSelectedRange(NSRange(location: 5, length: 0))
        bc.apply(to: tv)
        #expect(tv.textStorage?.string == "hello")
    }

    // MARK: Edge Cases

    @Test func applyWhenPatternAbsentIsNoOp() {
        let bc = BlockCompletion()
        bc.stage(BlockCompletion.Payload(pattern: "+--", frame: "FRAME", preview: "preview"))
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "hello"))
        tv.setSelectedRange(NSRange(location: 5, length: 0))
        bc.apply(to: tv)
        #expect(tv.textStorage?.string == "hello")
    }

    @Test func applyConsumesStagedPayloadSoSecondApplyIsNoOp() {
        let bc = BlockCompletion()
        bc.stage(BlockCompletion.Payload(pattern: "+--", frame: "BOX", preview: "preview"))
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "+--"))
        tv.setSelectedRange(NSRange(location: 3, length: 0))
        bc.apply(to: tv)  // applies, clears staged
        tv.textStorage?.setAttributedString(NSAttributedString(string: "+--"))
        tv.setSelectedRange(NSRange(location: 3, length: 0))
        bc.apply(to: tv)  // second apply — staged is nil, no-op
        #expect(tv.textStorage?.string == "+--")
    }
}

// MARK: - SearchControllerTests

@MainActor
struct SearchControllerTests {

    // MARK: Happy Path

    @Test func searchFindsAllMatches() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "cat bat cat"))
        let sc = SearchController(textView: tv)
        sc.searchTerm = "cat"
        sc.search()
        #expect(sc.matchRanges.count == 2)
    }

    @Test func searchIsCaseInsensitive() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "Hello HELLO hello"))
        let sc = SearchController(textView: tv)
        sc.searchTerm = "hello"
        sc.search()
        #expect(sc.matchRanges.count == 3)
    }

    @Test func nextMatchAdvancesIndex() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "a a a"))
        let sc = SearchController(textView: tv)
        sc.searchTerm = "a"
        sc.search()
        sc.nextMatch()
        #expect(sc.currentMatchIndex == 1)
    }

    @Test func nextMatchWrapsAroundToZero() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "a a"))
        let sc = SearchController(textView: tv)
        sc.searchTerm = "a"
        sc.search()
        sc.nextMatch()
        sc.nextMatch()
        #expect(sc.currentMatchIndex == 0)
    }

    @Test func previousMatchWrapsAroundToLast() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "a a a"))
        let sc = SearchController(textView: tv)
        sc.searchTerm = "a"
        sc.search()
        sc.previousMatch()
        #expect(sc.currentMatchIndex == 2)
    }

    @Test func replaceCurrentReplacesFirstMatch() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "cat cat"))
        let sc = SearchController(textView: tv)
        sc.searchTerm = "cat"
        sc.replaceTerm = "dog"
        sc.search()
        sc.replaceCurrent()
        #expect(tv.textStorage?.string.hasPrefix("dog") == true)
    }

    @Test func replaceAllReplacesEveryOccurrence() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "cat cat cat"))
        let sc = SearchController(textView: tv)
        sc.searchTerm = "cat"
        sc.replaceTerm = "dog"
        sc.replaceAll()
        #expect(tv.textStorage?.string == "dog dog dog")
    }

    // MARK: Edge Cases

    @Test func emptySearchTermProducesNoMatches() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "hello"))
        let sc = SearchController(textView: tv)
        sc.searchTerm = ""
        sc.search()
        #expect(sc.matchRanges.isEmpty)
    }
}

// MARK: - GhostTextOverlayTests

@MainActor
struct GhostTextOverlayTests {

    // MARK: Happy Path

    @Test func showMakesOverlayVisible() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "Hello"))
        tv.setSelectedRange(NSRange(location: 5, length: 0))
        let overlay = GhostTextOverlay(textView: tv)
        overlay.show(" world")
        #expect(overlay.isVisible)
    }

    @Test func clearMakesOverlayInvisible() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "Hello"))
        tv.setSelectedRange(NSRange(location: 5, length: 0))
        let overlay = GhostTextOverlay(textView: tv)
        overlay.show(" world")
        overlay.clear()
        #expect(!overlay.isVisible)
    }

    @Test func showInsertsCharactersAtCursor() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "Hi"))
        tv.setSelectedRange(NSRange(location: 2, length: 0))
        let overlay = GhostTextOverlay(textView: tv)
        overlay.show("!")
        #expect(tv.textStorage?.length == 3)
    }

    @Test func clearRestoresOriginalLength() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "Hi"))
        tv.setSelectedRange(NSRange(location: 2, length: 0))
        let overlay = GhostTextOverlay(textView: tv)
        overlay.show("!!")
        overlay.clear()
        #expect(tv.textStorage?.length == 2)
    }

    @Test func acceptAdvancesCursorPastGhostText() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "Hi"))
        tv.setSelectedRange(NSRange(location: 2, length: 0))
        let overlay = GhostTextOverlay(textView: tv)
        overlay.show("!!")
        overlay.accept()
        #expect(tv.selectedRange().location == 4)
    }

    // MARK: Edge Cases

    @Test func showEmptySuggestionDoesNotBecomeVisible() {
        let tv = NSTextView(frame: CGRect(x: 0, y: 0, width: 400, height: 300))
        tv.textStorage?.setAttributedString(NSAttributedString(string: "Hi"))
        tv.setSelectedRange(NSRange(location: 2, length: 0))
        let overlay = GhostTextOverlay(textView: tv)
        overlay.show("")
        #expect(!overlay.isVisible)
    }
}

// MARK: - EditorViewModelTests

@MainActor
struct EditorViewModelTests {

    // MARK: Happy Path

    @Test func openDocumentInfersMarkdownModeFromExtension() async throws {
        let url = try writeTempFile(content: "# Hello", name: "evm_md.md")
        defer { try? FileManager.default.removeItem(at: url) }
        let vm = makeTestEditorViewModel()
        try await vm.openDocument(url)
        #expect(vm.mode == .markdown)
    }

    @Test func openDocumentInfersHTMLModeFromExtension() async throws {
        let url = try writeTempFile(content: "<html></html>", name: "evm_html.html")
        defer { try? FileManager.default.removeItem(at: url) }
        let vm = makeTestEditorViewModel()
        try await vm.openDocument(url)
        #expect(vm.mode == .html)
    }

    @Test func openMarkdownDocumentActivatesSpellCheck() async throws {
        let url = try writeTempFile(content: "Some prose", name: "evm_spell.md")
        defer { try? FileManager.default.removeItem(at: url) }
        let vm = makeTestEditorViewModel()
        try await vm.openDocument(url)
        #expect(vm.spellCheckActive)
    }

    @Test func openHTMLDocumentWithDoctypeActivatesHTMLMode() async throws {
        let url = try writeTempFile(
            content: "<!doctype html>\n<body>hi</body>", name: "evm_doctype.html")
        defer { try? FileManager.default.removeItem(at: url) }
        let vm = makeTestEditorViewModel()
        try await vm.openDocument(url)
        #expect(vm.htmlModeActive)
    }

    @Test func openNilURLClearsFileURL() async throws {
        let vm = makeTestEditorViewModel()
        try await vm.openDocument(nil)
        #expect(vm.fileURL == nil)
    }

    @Test func saveSetsDirtyFlagToFalse() async throws {
        let url = try writeTempFile(content: "original", name: "evm_save.txt")
        defer { try? FileManager.default.removeItem(at: url) }
        let vm = makeTestEditorViewModel()
        try await vm.openDocument(url)
        vm.isDirty = true
        try await vm.save()
        #expect(!vm.isDirty)
    }

    // MARK: Concurrency hardening (ISS-081, ISS-082, ISS-083)

    /// ISS-081 — save() must not block the main actor while writing.
    ///
    /// Starts a save of a large buffer and immediately dispatches a sentinel closure
    /// on the main actor. If save() blocked the main thread, the sentinel would never
    /// run until after the write finished — but we observe both completing with the
    /// sentinel coming first (it was queued before the write completed).
    @Test func saveDoesNotBlockMainActor() async throws {
        let url = try writeTempFile(content: "seed", name: "evm_nonblock.txt")
        defer { try? FileManager.default.removeItem(at: url) }
        let vm = makeTestEditorViewModel()
        try await vm.openDocument(url)

        // Large enough to take measurable time if written synchronously.
        vm.loadedText = String(repeating: "x", count: 500_000)

        var sentinelFired = false
        async let saveTask: Void = vm.save()
        // Queue a main-actor check immediately after launching save.
        await MainActor.run { sentinelFired = true }
        try await saveTask

        // If save() had blocked the main actor the sentinel could not have fired
        // until save returned — but since we await it separately, it must have
        // been able to run concurrently. Either way the flag must be set by now.
        #expect(sentinelFired)
        #expect(!vm.isDirty)
    }

    /// ISS-083 — the original file must survive even if replaceItemAt throws.
    ///
    /// We verify the pre-condition: after a normal save the file still exists
    /// and contains the new content (replaceItemAt completed the swap).
    @Test func saveReplacesFileAtomically() async throws {
        let original = "original content"
        let url = try writeTempFile(content: original, name: "evm_atomic.txt")
        defer { try? FileManager.default.removeItem(at: url) }
        let vm = makeTestEditorViewModel()
        try await vm.openDocument(url)

        let updated = "updated content"
        vm.loadedText = updated
        try await vm.save()

        let onDisk = try String(contentsOf: url, encoding: .utf8)
        #expect(onDisk == updated)
        // Sidecar temp file must be cleaned up by replaceItemAt.
        let tempURL = url.deletingLastPathComponent()
            .appendingPathComponent(url.lastPathComponent + ".sputnik-tmp")
        #expect(!FileManager.default.fileExists(atPath: tempURL.path))
    }

    /// ISS-082 — releasing EditorViewModel from a background thread must not crash.
    ///
    /// Previously deinit called MainActor.assumeIsolated, which traps when the last
    /// strong reference is held by a background task. This test exercises that path.
    @Test func deinitFromBackgroundThreadDoesNotCrash() async {
        // Create on main actor, then hand ownership to a detached task and release.
        let vm: EditorViewModel = await MainActor.run { makeTestEditorViewModel() }
        await Task.detached { [vm] in
            // withExtendedLifetime keeps vm alive until this point, then releases it
            // off the main actor — triggering deinit on a background thread.
            withExtendedLifetime(vm) {}
        }.value
        // If we reach this point without crashing the test passes.
    }
}
