// ResourcesModuleTests.swift
// Generated by !CreateTests skill — review before merging

import Testing
import AppKit
import Foundation
@testable import ResourcesModule

// MARK: - ASCIIArtRecordTests

struct ASCIIArtRecordTests {

    // MARK: Happy Path

    @Test func initStoresAllProperties() {
        let record = ASCIIArtRecord(
            id: "arrows/simple-right",
            title: "Simple Right Arrow",
            tags: ["arrow", "right"],
            category: "Arrows",
            filename: "Arrows/simple_right.txt"
        )
        #expect(record.id == "arrows/simple-right")
        #expect(record.title == "Simple Right Arrow")
        #expect(record.tags == ["arrow", "right"])
        #expect(record.category == "Arrows")
        #expect(record.filename == "Arrows/simple_right.txt")
    }

    @Test func codableRoundTrip() throws {
        let record = ASCIIArtRecord(id: "misc/dot", title: "Dot", tags: ["small"], category: "Misc", filename: "Misc/dot.txt")
        let data = try JSONEncoder().encode(record)
        let decoded = try JSONDecoder().decode(ASCIIArtRecord.self, from: data)
        #expect(decoded.id == "misc/dot")
        #expect(decoded.tags == ["small"])
    }

    // MARK: Edge Cases

    @Test func emptyTagsIsValid() {
        let record = ASCIIArtRecord(id: "x", title: "X", tags: [], category: "Cat", filename: "x.txt")
        #expect(record.tags.isEmpty)
    }

    @Test func hashableEqualForIdenticalValues() {
        let a = ASCIIArtRecord(id: "x", title: "T", tags: [], category: "C", filename: "f.txt")
        let b = ASCIIArtRecord(id: "x", title: "T", tags: [], category: "C", filename: "f.txt")
        #expect(a == b)
        #expect(a.hashValue == b.hashValue)
    }

    @Test func hashableDistinctForDifferentIDs() {
        let a = ASCIIArtRecord(id: "x", title: "T", tags: [], category: "C", filename: "f.txt")
        let b = ASCIIArtRecord(id: "y", title: "T", tags: [], category: "C", filename: "f.txt")
        #expect(a != b)
    }
}

// MARK: - ASCIILibraryIndexTests

struct ASCIILibraryIndexTests {

    @Test func initStoresRecords() {
        let record = ASCIIArtRecord(id: "a", title: "A", tags: [], category: "C", filename: "a.txt")
        let index = ASCIILibraryIndex(records: [record])
        #expect(index.records.count == 1)
        #expect(index.records[0].id == "a")
    }

    @Test func emptyRecordsArray() {
        let index = ASCIILibraryIndex(records: [])
        #expect(index.records.isEmpty)
    }

    @Test func codableRoundTrip() throws {
        let record = ASCIIArtRecord(id: "b", title: "B", tags: ["tag"], category: "Cat", filename: "b.txt")
        let index = ASCIILibraryIndex(records: [record])
        let data = try JSONEncoder().encode(index)
        let decoded = try JSONDecoder().decode(ASCIILibraryIndex.self, from: data)
        #expect(decoded.records.count == 1)
        #expect(decoded.records[0].id == "b")
        #expect(decoded.records[0].tags == ["tag"])
    }
}

// MARK: - MarkdownHelpContentTests

struct MarkdownHelpContentTests {

    @Test func initStoresAllFields() {
        let topic = MarkdownHelpContent(
            id: "basics/headings",
            title: "Headings",
            category: "basics",
            body: "# H1",
            searchTerms: ["heading", "h1"],
            relatedTopics: ["formatting/bold"],
            exampleCode: "# Title"
        )
        #expect(topic.id == "basics/headings")
        #expect(topic.title == "Headings")
        #expect(topic.category == "basics")
        #expect(topic.exampleCode == "# Title")
        #expect(topic.searchTerms.count == 2)
    }

    @Test func defaultsSearchTermsToEmpty() {
        let topic = MarkdownHelpContent(id: "a", title: "A", category: "b", body: "c")
        #expect(topic.searchTerms.isEmpty)
    }

    @Test func defaultsRelatedTopicsToEmpty() {
        let topic = MarkdownHelpContent(id: "a", title: "A", category: "b", body: "c")
        #expect(topic.relatedTopics.isEmpty)
    }

    @Test func defaultsExampleCodeToNil() {
        let topic = MarkdownHelpContent(id: "a", title: "A", category: "b", body: "c")
        #expect(topic.exampleCode == nil)
    }

    @Test func codableRoundTrip() throws {
        // swiftformat:disable:next all
        let json = "{\"id\":\"basics/headings\",\"title\":\"Headings\",\"category\":\"basics\",\"body\":\"## H2\",\"searchTerms\":[\"heading\"],\"relatedTopics\":[],\"exampleCode\":null}".data(using: .utf8)!
        let decoded = try JSONDecoder().decode(MarkdownHelpContent.self, from: json)
        #expect(decoded.id == "basics/headings")
        #expect(decoded.searchTerms == ["heading"])
        #expect(decoded.exampleCode == nil)
    }
}

// MARK: - HTMLHelpContentTests

struct HTMLHelpContentTests {

    @Test func initStoresAllFields() {
        let topic = HTMLHelpContent(
            id: "elements/links",
            title: "Links",
            category: "elements",
            body: "The `<a>` tag.",
            searchTerms: ["link", "href"],
            relatedTopics: ["elements/images"],
            exampleHTML: "<a href='#'>Click</a>"
        )
        #expect(topic.id == "elements/links")
        #expect(topic.exampleHTML == "<a href='#'>Click</a>")
        #expect(topic.searchTerms.count == 2)
    }

    @Test func defaultsExampleHTMLToNil() {
        let topic = HTMLHelpContent(id: "a", title: "A", category: "b", body: "c")
        #expect(topic.exampleHTML == nil)
    }

    @Test func defaultsSearchTermsToEmpty() {
        let topic = HTMLHelpContent(id: "a", title: "A", category: "b", body: "c")
        #expect(topic.searchTerms.isEmpty)
    }
}

// MARK: - GrammarHelpContentTests

struct GrammarHelpContentTests {

    @Test func initStoresAllFields() {
        let topic = GrammarHelpContent(
            id: "spelling/their",
            title: "Their / There / They're",
            category: "spelling",
            body: "Use **their** for possession.",
            searchTerms: ["their", "there", "they're"],
            relatedTopics: ["spelling/its"]
        )
        #expect(topic.id == "spelling/their")
        #expect(topic.searchTerms.count == 3)
        #expect(topic.searchTerms.contains("their"))
    }

    @Test func defaultsSearchTermsToEmpty() {
        let topic = GrammarHelpContent(id: "a", title: "A", category: "b", body: "c")
        #expect(topic.searchTerms.isEmpty)
    }

    @Test func defaultsRelatedTopicsToEmpty() {
        let topic = GrammarHelpContent(id: "a", title: "A", category: "b", body: "c")
        #expect(topic.relatedTopics.isEmpty)
    }
}

// MARK: - ASCIIArtHelpContentTests

struct ASCIIArtHelpContentTests {

    @Test func initStoresAllFields() {
        let topic = ASCIIArtHelpContent(
            id: "basics/shapes",
            title: "Drawing Shapes",
            category: "basics",
            body: "Use `+` for corners.",
            searchTerms: ["shape", "box"],
            relatedTopics: ["basics/lines"],
            relatedArtIDs: ["shapes/box"],
            exampleCode: "+--+\n|  |\n+--+"
        )
        #expect(topic.id == "basics/shapes")
        #expect(topic.relatedArtIDs == ["shapes/box"])
        #expect(topic.exampleCode == "+--+\n|  |\n+--+")
        #expect(topic.searchTerms.count == 2)
    }

    @Test func defaultsRelatedArtIDsToEmpty() {
        let topic = ASCIIArtHelpContent(id: "a", title: "A", category: "b", body: "c")
        #expect(topic.relatedArtIDs.isEmpty)
    }

    @Test func defaultsExampleCodeToNil() {
        let topic = ASCIIArtHelpContent(id: "a", title: "A", category: "b", body: "c")
        #expect(topic.exampleCode == nil)
    }

    @Test func defaultsSearchTermsToEmpty() {
        let topic = ASCIIArtHelpContent(id: "a", title: "A", category: "b", body: "c")
        #expect(topic.searchTerms.isEmpty)
    }
}

// MARK: - GrammarHelpLookupResultTests

struct GrammarHelpLookupResultTests {

    @Test func storesPrimaryTopic() {
        let primary = GrammarHelpContent(id: "a", title: "A", category: "b", body: "c")
        let result = GrammarHelpLookupResult(primaryTopic: primary, alternatives: [], source: .editor)
        #expect(result.primaryTopic.id == "a")
    }

    @Test func storesAlternatives() {
        let primary = GrammarHelpContent(id: "a", title: "A", category: "b", body: "c")
        let alts = [
            GrammarHelpContent(id: "b", title: "B", category: "b", body: "d"),
            GrammarHelpContent(id: "c", title: "C", category: "b", body: "e"),
        ]
        let result = GrammarHelpLookupResult(primaryTopic: primary, alternatives: alts, source: .editor)
        #expect(result.alternatives.count == 2)
    }

    @Test func storesSource() {
        let primary = GrammarHelpContent(id: "a", title: "A", category: "b", body: "c")
        let editorResult = GrammarHelpLookupResult(primaryTopic: primary, alternatives: [], source: .editor)
        let previewResult = GrammarHelpLookupResult(primaryTopic: primary, alternatives: [], source: .markdownPreview)
        let htmlResult = GrammarHelpLookupResult(primaryTopic: primary, alternatives: [], source: .htmlPreview)
        #expect(editorResult.source == .editor)
        #expect(previewResult.source == .markdownPreview)
        #expect(htmlResult.source == .htmlPreview)
    }
}

// MARK: - HelpTabStateTests

struct HelpTabStateTests {

    @Test func initStoresFields() {
        let state = HelpTabState(topicID: "basics/headings", title: "Headings")
        #expect(state.topicID == "basics/headings")
        #expect(state.title == "Headings")
    }

    @Test func codableRoundTrip() throws {
        let state = HelpTabState(topicID: "advanced/tables", title: "Tables")
        let data = try JSONEncoder().encode(state)
        let decoded = try JSONDecoder().decode(HelpTabState.self, from: data)
        #expect(decoded.topicID == "advanced/tables")
        #expect(decoded.title == "Tables")
    }
}

// MARK: - HelpPanelPersistedStateTests

struct HelpPanelPersistedStateTests {

    @Test func defaultsToEmptyTabsAndNilActiveID() {
        let state = HelpPanelPersistedState()
        #expect(state.tabs.isEmpty)
        #expect(state.activeTabID == nil)
    }

    @Test func codableRoundTripWithTabs() throws {
        let tab = HelpTabState(topicID: "basics/headings", title: "Headings")
        let state = HelpPanelPersistedState(tabs: [tab], activeTabID: "basics/headings")
        let data = try JSONEncoder().encode(state)
        let decoded = try JSONDecoder().decode(HelpPanelPersistedState.self, from: data)
        #expect(decoded.tabs.count == 1)
        #expect(decoded.activeTabID == "basics/headings")
    }
}

// MARK: - MarkdownHelpCoordinatorTests

@MainActor
struct MarkdownHelpCoordinatorTests {

    // MARK: Happy Path — Syntax Detection

    @Test func detectsH1HeadingOnLine() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "# My Title",
            cursorOffset: 5,
            selectedText: nil
        )
        #expect(id == "basics/headings")
    }

    @Test func detectsBoldAsterisks() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "**bold text**",
            cursorOffset: 5,
            selectedText: nil
        )
        #expect(id == "formatting/bold-and-italic")
    }

    @Test func detectsInlineCode() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "use `print()` here",
            cursorOffset: 7,
            selectedText: nil
        )
        #expect(id == "formatting/code")
    }

    @Test func detectsLink() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "[click here](https://example.com)",
            cursorOffset: 5,
            selectedText: nil
        )
        #expect(id == "formatting/links")
    }

    @Test func detectsImage() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "![alt](img.png)",
            cursorOffset: 3,
            selectedText: nil
        )
        #expect(id == "formatting/images")
    }

    @Test func detectsUnorderedList() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "- item one",
            cursorOffset: 5,
            selectedText: nil
        )
        #expect(id == "formatting/lists")
    }

    @Test func detectsBlockquote() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "> quoted text",
            cursorOffset: 5,
            selectedText: nil
        )
        #expect(id == "advanced/blockquotes")
    }

    @Test func detectsCodeBlock() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "```swift\nlet x = 1\n```",
            cursorOffset: 3,
            selectedText: nil
        )
        #expect(id == "advanced/code-blocks")
    }

    @Test func detectsTable() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "| Col1 | Col2 |",
            cursorOffset: 3,
            selectedText: nil
        )
        #expect(id == "advanced/tables")
    }

    @Test func detectsHorizontalRule() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "---",
            cursorOffset: 1,
            selectedText: nil
        )
        #expect(id == "advanced/horizontal-rules")
    }

    // MARK: Keyword Selection

    @Test func selectedKeywordHeadingMapsToHeadingsTopic() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "some text",
            cursorOffset: 5,
            selectedText: "heading"
        )
        #expect(id == "basics/headings")
    }

    @Test func selectedKeywordBoldMapsToFormattingTopic() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "some text",
            cursorOffset: 5,
            selectedText: "bold"
        )
        #expect(id == "formatting/bold-and-italic")
    }

    @Test func selectedKeywordTableMapsToTablesTopic() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "some text",
            cursorOffset: 5,
            selectedText: "table"
        )
        #expect(id == "advanced/tables")
    }

    @Test func selectedKeywordMarkdownMapsToGettingStarted() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "",
            cursorOffset: 0,
            selectedText: "markdown"
        )
        #expect(id == "basics/getting-started")
    }

    @Test func selectedKeywordIsCaseInsensitive() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "",
            cursorOffset: 0,
            selectedText: "HEADING"
        )
        #expect(id == "basics/headings")
    }

    @Test func selectedKeywordLinkMapsToLinksTopic() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "",
            cursorOffset: 0,
            selectedText: "link"
        )
        #expect(id == "formatting/links")
    }

    // MARK: Edge Cases

    @Test func unknownSelectedKeywordFallsThroughToLineScan() {
        // "plain text" has no markdown syntax, so nil is expected
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "plain text",
            cursorOffset: 4,
            selectedText: "unknown"
        )
        #expect(id == nil)
    }

    @Test func outOfRangeCursorReturnsNil() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "# hello",
            cursorOffset: 999,
            selectedText: nil
        )
        #expect(id == nil)
    }

    @Test func emptyDocumentReturnsNil() {
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "",
            cursorOffset: 0,
            selectedText: nil
        )
        #expect(id == nil)
    }

    @Test func multilineTextFindsCorrectLine() {
        // Offset 14 lands inside "## Section heading" (line 2)
        let id = MarkdownHelpCoordinator.shared.lookupContext(
            fullText: "plain text\n## Section heading",
            cursorOffset: 14,
            selectedText: nil
        )
        #expect(id == "basics/headings")
    }
}

// MARK: - HTMLHelpCoordinatorTests

@MainActor
struct HTMLHelpCoordinatorTests {

    // MARK: Tag Matching

    @Test func selectedDivReturnsDivAndSpanTopic() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "div"
        )
        #expect(id == "elements/div-and-span")
    }

    @Test func selectedTableReturnsTablesTopic() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "table"
        )
        #expect(id == "elements/tables")
    }

    @Test func selectedInputReturnsFormsTopic() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "input"
        )
        #expect(id == "elements/forms")
    }

    @Test func selectedH2ReturnsHeadingsTopic() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "h2"
        )
        #expect(id == "elements/headings")
    }

    @Test func selectedUlReturnsListsTopic() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "ul"
        )
        #expect(id == "elements/lists")
    }

    @Test func selectedImgReturnsImagesTopic() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "img"
        )
        #expect(id == "elements/images")
    }

    // MARK: Attribute Matching

    @Test func selectedClassReturnsClassAndIDTopic() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "class"
        )
        #expect(id == "attributes/class-and-id")
    }

    @Test func selectedIDReturnsClassAndIDTopic() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "id"
        )
        #expect(id == "attributes/class-and-id")
    }

    @Test func selectedStyleReturnsStyleTopic() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "style"
        )
        #expect(id == "attributes/style")
    }

    @Test func selectedHrefReturnsLinksTopic() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "href"
        )
        #expect(id == "elements/links")
    }

    // MARK: Pattern Matching

    @Test func selectedDataAttributeReturnsDataTopic() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "data-custom-attr"
        )
        #expect(id == "globals/data-attributes")
    }

    @Test func selectedOnClickReturnsEventsTopic() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "onclick"
        )
        #expect(id == "events/onclick-and-events")
    }

    @Test func selectedOnPrefixReturnsEventsTopic() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "onmouseover"
        )
        #expect(id == "events/onclick-and-events")
    }

    // MARK: Edge Cases

    @Test func unknownTokenReturnsNil() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "foobar"
        )
        #expect(id == nil)
    }

    @Test func tagMatchIsCaseInsensitive() {
        let id = HTMLHelpCoordinator.shared.lookupContext(
            fullText: "", cursorOffset: 0, selectedText: "DIV"
        )
        #expect(id == "elements/div-and-span")
    }
}

// MARK: - PreviewImageResolverTests

struct PreviewImageResolverTests {

    // MARK: Path Safety — all return .notFound without touching disk

    @Test func httpURLReturnsNotFound() async {
        let resolver = PreviewImageResolver()
        let result = await resolver.resolve(reference: "http://example.com/img.png", relativeTo: .temporaryDirectory)
        #expect(result.isNotFound)
    }

    @Test func httpsURLReturnsNotFound() async {
        let resolver = PreviewImageResolver()
        let result = await resolver.resolve(reference: "https://example.com/img.png", relativeTo: .temporaryDirectory)
        #expect(result.isNotFound)
    }

    @Test func dataURIReturnsNotFound() async {
        let resolver = PreviewImageResolver()
        let result = await resolver.resolve(reference: "data:image/png;base64,abc", relativeTo: .temporaryDirectory)
        #expect(result.isNotFound)
    }

    @Test func absolutePathReturnsNotFound() async {
        let resolver = PreviewImageResolver()
        let result = await resolver.resolve(reference: "/tmp/image.png", relativeTo: .temporaryDirectory)
        #expect(result.isNotFound)
    }

    @Test func dotDotEscapeReturnsNotFound() async {
        let resolver = PreviewImageResolver()
        let result = await resolver.resolve(reference: "../etc/passwd", relativeTo: .temporaryDirectory)
        #expect(result.isNotFound)
    }

    @Test func embeddedDotDotReturnsNotFound() async {
        let resolver = PreviewImageResolver()
        let result = await resolver.resolve(reference: "imgs/../../../etc/shadow", relativeTo: .temporaryDirectory)
        #expect(result.isNotFound)
    }

    @Test func nonExistentRelativeFileReturnsNotFound() async {
        let resolver = PreviewImageResolver()
        let result = await resolver.resolve(reference: "no_such_file_sputnik.png", relativeTo: .temporaryDirectory)
        #expect(result.isNotFound)
    }

    // MARK: Happy Path

    @Test func validPNGFileReturnsImage() async throws {
        let resolver = PreviewImageResolver()
        let dir = URL.temporaryDirectory
        let imageURL = dir.appendingPathComponent("sputnik_test_img.png")

        let bitmapRep = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: 2,
            pixelsHigh: 2,
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        )
        let pngData = try #require(bitmapRep?.representation(using: .png, properties: [:]))
        try pngData.write(to: imageURL)
        defer { try? FileManager.default.removeItem(at: imageURL) }

        let result = await resolver.resolve(reference: "sputnik_test_img.png", relativeTo: dir)
        #expect(result.isImage)
    }

    // MARK: Convenience Methods

    @Test func nsImageReturnsNilForNotFound() async {
        let resolver = PreviewImageResolver()
        let result = await resolver.nsImage(reference: "nonexistent.png", relativeTo: .temporaryDirectory)
        #expect(result == nil)
    }

    @Test func dataReturnsNilForNotFound() async {
        let resolver = PreviewImageResolver()
        let result = await resolver.data(reference: "nonexistent.png", relativeTo: .temporaryDirectory)
        #expect(result == nil)
    }
}

// MARK: - ResolvedImage helpers

extension PreviewImageResolver.ResolvedImage {
    var isNotFound: Bool {
        if case .notFound = self { return true }
        return false
    }
    var isImage: Bool {
        if case .image = self { return true }
        return false
    }
}

// MARK: - HelpExternalSearchBuilderTests

struct HelpExternalSearchBuilderTests {

    // MARK: URL structure

    @Test func grammarTopicProducesGoogleSearchURL() {
        let links = HelpExternalSearchBuilder.build(
            title: "Subject and Predicate",
            searchTerms: ["sentence subject", "predicate"],
            kind: .grammar
        )
        #expect(!links.isEmpty)
        #expect(links[0].url.scheme == "https")
        #expect(links[0].url.host == "www.google.com")
        #expect(links[0].url.path == "/search")
    }

    @Test func urlContainsPercentEncodedTitle() {
        let links = HelpExternalSearchBuilder.build(
            title: "Subject and Predicate",
            searchTerms: [],
            kind: .grammar
        )
        let query = links.first.flatMap { URLComponents(url: $0.url, resolvingAgainstBaseURL: false) }?
            .queryItems?.first(where: { $0.name == "q" })?.value
        #expect(query?.contains("Subject and Predicate") == true)
    }

    // MARK: Context word per kind

    @Test func grammarContextWordIsGrammar() {
        #expect(HelpExternalSearchBuilder.contextWord(for: .grammar) == "grammar")
    }

    @Test func markdownContextWordIsMarkdownSyntax() {
        #expect(HelpExternalSearchBuilder.contextWord(for: .markdown) == "markdown syntax")
    }

    @Test func htmlContextWordIsHTML() {
        #expect(HelpExternalSearchBuilder.contextWord(for: .html) == "HTML")
    }

    @Test func jsonContextWordIsJSON() {
        #expect(HelpExternalSearchBuilder.contextWord(for: .json) == "JSON")
    }

    @Test func asciiArtContextWordIsASCIIArt() {
        #expect(HelpExternalSearchBuilder.contextWord(for: .asciiArt) == "ASCII art")
    }

    @Test func sputnikContextWordIsEmpty() {
        #expect(HelpExternalSearchBuilder.contextWord(for: .sputnik) == "")
    }

    // MARK: Context word appears in query

    @Test func grammarQueryContainsContextWord() {
        let links = HelpExternalSearchBuilder.build(
            title: "Comma Usage",
            searchTerms: [],
            kind: .grammar
        )
        let query = links.first.flatMap { URLComponents(url: $0.url, resolvingAgainstBaseURL: false) }?
            .queryItems?.first(where: { $0.name == "q" })?.value
        #expect(query?.contains("grammar") == true)
    }

    @Test func markdownQueryContainsContextWord() {
        let links = HelpExternalSearchBuilder.build(
            title: "Headings",
            searchTerms: [],
            kind: .markdown
        )
        let query = links.first.flatMap { URLComponents(url: $0.url, resolvingAgainstBaseURL: false) }?
            .queryItems?.first(where: { $0.name == "q" })?.value
        #expect(query?.contains("markdown syntax") == true)
    }

    @Test func htmlQueryContainsContextWord() {
        let links = HelpExternalSearchBuilder.build(
            title: "Links",
            searchTerms: [],
            kind: .html
        )
        let query = links.first.flatMap { URLComponents(url: $0.url, resolvingAgainstBaseURL: false) }?
            .queryItems?.first(where: { $0.name == "q" })?.value
        #expect(query?.contains("HTML") == true)
    }

    // MARK: Link count

    @Test func noSearchTermsProducesOneLink() {
        let links = HelpExternalSearchBuilder.build(
            title: "Semicolons",
            searchTerms: [],
            kind: .grammar
        )
        #expect(links.count == 1)
    }

    @Test func distinctSearchTermProducesTwoLinks() {
        let links = HelpExternalSearchBuilder.build(
            title: "Their / There / They're",
            searchTerms: ["their", "there", "they're"],
            kind: .grammar
        )
        #expect(links.count == 2)
    }

    @Test func atMostTwoLinksReturned() {
        let links = HelpExternalSearchBuilder.build(
            title: "Commas",
            searchTerms: ["comma", "serial comma", "Oxford comma", "list comma"],
            kind: .grammar
        )
        #expect(links.count <= 2)
    }

    @Test func searchTermIdenticalToTitleProducesOneLink() {
        let links = HelpExternalSearchBuilder.build(
            title: "Commas",
            searchTerms: ["commas"],
            kind: .grammar
        )
        #expect(links.count == 1)
    }

    @Test func searchTermIdenticalToTitleCaseInsensitive() {
        let links = HelpExternalSearchBuilder.build(
            title: "Commas",
            searchTerms: ["COMMAS"],
            kind: .grammar
        )
        #expect(links.count == 1)
    }

    // MARK: Edge / crash-safety

    @Test func emptyTitleReturnsEmpty() {
        let links = HelpExternalSearchBuilder.build(
            title: "",
            searchTerms: ["some term"],
            kind: .grammar
        )
        #expect(links.isEmpty)
    }

    @Test func whitespaceOnlyTitleReturnsEmpty() {
        let links = HelpExternalSearchBuilder.build(
            title: "   ",
            searchTerms: [],
            kind: .grammar
        )
        #expect(links.isEmpty)
    }

    @Test func emptySearchTermsDoesNotCrash() {
        let links = HelpExternalSearchBuilder.build(
            title: "Bold Text",
            searchTerms: [],
            kind: .markdown
        )
        #expect(links.count == 1)
    }

    // MARK: Label format

    @Test func labelContainsTitleAndContextWord() {
        let links = HelpExternalSearchBuilder.build(
            title: "Colons",
            searchTerms: [],
            kind: .grammar
        )
        #expect(links[0].label.contains("Colons"))
        #expect(links[0].label.contains("grammar"))
    }

    @Test func secondLinkLabelContainsExamples() {
        let links = HelpExternalSearchBuilder.build(
            title: "Colons",
            searchTerms: ["colon usage"],
            kind: .grammar
        )
        #expect(links.count == 2)
        #expect(links[1].label.contains("examples"))
    }
}

// MARK: - GrammarHelpIndexTests

struct GrammarHelpIndexTests {

    // Tests that the empty-term guard fires before any bundle access attempt.

    @Test func searchByTermReturnsEmptyForBlankString() async {
        let results = await GrammarHelpIndex.shared.searchByTerm("")
        #expect(results.isEmpty)
    }

    @Test func searchByTermReturnsEmptyForWhitespaceOnly() async {
        let results = await GrammarHelpIndex.shared.searchByTerm("   ")
        #expect(results.isEmpty)
    }

    // MARK: - Structural-Aware Search

    @Test func structuralBoostPrioritizesStructuralTopics() async {
        let standardResults = await GrammarHelpIndex.shared.searchByTerm("subject")
        let structuralResults = await GrammarHelpIndex.shared.searchByTerm("subject", preferStructural: true)

        // Both should return results
        #expect(!standardResults.isEmpty)
        #expect(!structuralResults.isEmpty)

        // Structural search should prioritize structural topics higher
        // The first result should ideally be a structural topic when preferStructural is true
        if let firstStructural = structuralResults.first {
            #expect(firstStructural.structuralLevel == .structural)
        }
    }

    @Test func structuralLevelFieldDecodes() async {
        let topics = await GrammarHelpIndex.shared.allTopics()
        #expect(!topics.isEmpty)

        // All topics should have a structuralLevel set (defaults to .lexical)
        for topic in topics {
            #expect(topic.structuralLevel == .lexical || topic.structuralLevel == .structural)
        }

        // There should be at least some structural topics
        let structuralTopics = topics.filter { $0.structuralLevel == .structural }
        #expect(!structuralTopics.isEmpty)
    }

    @Test func allStructuralTopicsAreMarked() async {
        let topics = await GrammarHelpIndex.shared.allTopics()
        let structuralIDs = Set([
            "sentence-structure/clause-types",
            "sentence-structure/diagramming-basics",
            "sentence-structure/direct-and-indirect-objects",
            "sentence-structure/phrase-types",
            "sentence-structure/sentence-types",
            "sentence-structure/subject-and-predicate",
            "grammar/subject-verb-agreement",
            "grammar/dangling-modifiers",
            "grammar/conjunctions",
            "grammar/prepositions",
            "grammar/articles-a-an-the",
            "punctuation/apostrophes",
            "punctuation/colons",
            "punctuation/commas",
            "punctuation/dashes-and-hyphens",
            "punctuation/parentheses-and-brackets",
            "punctuation/quotation-marks",
            "punctuation/semicolons"
        ])

        for topic in topics {
            if structuralIDs.contains(topic.id) {
                #expect(topic.structuralLevel == .structural,
                    "Expected \(topic.id) to be structural but was \(topic.structuralLevel)")
            }
        }
    }
}

// MARK: - GrammarSelectionAnalyzerTests

struct GrammarSelectionAnalyzerTests {

    // MARK: - Word Count Detection

    @Test func singleWordSelectionCountsAsOne() async {
        let analysis = await GrammarSelectionAnalyzer.analyze(
            fullText: "The cat sat on the mat",
            cursorOffset: 4,  // "cat"
            selectionLength: 3
        )
        #expect(analysis.wordCount == 1)
    }

    @Test func multiWordSelectionCountsCorrectly() async {
        let analysis = await GrammarSelectionAnalyzer.analyze(
            fullText: "The cat sat on the mat",
            cursorOffset: 4,  // "cat sat on"
            selectionLength: 11
        )
        #expect(analysis.wordCount == 3)
    }

    @Test func zeroLengthSelectionCountsAsOne() async {
        let analysis = await GrammarSelectionAnalyzer.analyze(
            fullText: "The cat sat",
            cursorOffset: 0,
            selectionLength: 0
        )
        #expect(analysis.wordCount == 1)  // Empty string splits to [""] which counts as 1
    }

    // MARK: - Role Detection (Subject vs Object)

    @Test func nounPhraseBeforeVerbIsSubject() async {
        let text = "The cat sat"
        // "cat" is position 4, before main verb "sat"
        let analysis = await GrammarSelectionAnalyzer.analyze(
            fullText: text,
            cursorOffset: 4,
            selectionLength: 3
        )
        #expect(analysis.role == .subject)
    }

    @Test func nounPhraseAfterVerbIsObject() async {
        let text = "The cat sat on the mat"
        // "mat" is position 18, after main verb "sat"
        let analysis = await GrammarSelectionAnalyzer.analyze(
            fullText: text,
            cursorOffset: 18,
            selectionLength: 3
        )
        #expect(analysis.role == .object)
    }

    @Test func selectionWithoutVerbIsUnknown() async {
        let text = "Running quickly"  // Gerund + adverb, no finite verb
        let analysis = await GrammarSelectionAnalyzer.analyze(
            fullText: text,
            cursorOffset: 0,
            selectionLength: 7
        )
        #expect(analysis.role == .unknown)
    }

    // MARK: - Heuristic Limitations

    @Test func passiveVoiceMisclassifiesRole() async {
        // "The mat was sat on by the cat"
        // In passive voice, the original object appears first
        // This is a known heuristic limitation
        let text = "The mat was sat on by the cat"
        let analysis = await GrammarSelectionAnalyzer.analyze(
            fullText: text,
            cursorOffset: 4,  // "mat" — logically the object, but heuristic sees it before verb
            selectionLength: 3
        )
        // The heuristic will misclassify this — document as a limitation
        // Passive voice is expected to misclassify
        #expect(analysis.role == .subject)  // Heuristic says subject (before verb) — INCORRECT for passive
    }
}

// MARK: - GrammarHelpCoordinatorTests

struct GrammarHelpCoordinatorTests {

    @Test func singleWordSelectionUsesStandardSearch() async {
        let result = await GrammarHelpCoordinator.shared.lookup(
            word: "their",
            source: .editor,
            analysisResult: GrammarSelectionAnalyzer.AnalysisResult(wordCount: 1, role: .unknown)
        )

        #expect(result != nil)
        #expect(result?.primaryTopic.title.contains("Their") ?? false)
    }

    @Test func multiWordSelectionBootsStructuralTopics() async {
        // Looking up "subject predicate" — a multi-word structural phrase
        let result = await GrammarHelpCoordinator.shared.lookup(
            word: "subject",
            source: .editor,
            analysisResult: GrammarSelectionAnalyzer.AnalysisResult(wordCount: 2, role: .subject)
        )

        // With the structural boost, we should get a structural topic if one matches
        #expect(result != nil)
        if let primary = result?.primaryTopic {
            // If "subject" matched both a lexical and structural topic, structural should rank first
            #expect(primary.structuralLevel == .structural || primary.title.contains("Subject"))
        }
    }

    @Test func nilAnalysisResultDefaultsToStandardSearch() async {
        let result = await GrammarHelpCoordinator.shared.lookup(
            word: "their",
            source: .editor,
            analysisResult: nil
        )

        #expect(result != nil)
    }
}
