// PDFViewerModuleTests.swift
// Generated by !CreateTests skill — review before merging

import Testing
import PDFKit
import AppKit
@testable import PDFViewerModule

// MARK: - Test helpers

/// Integer-keyed subscript over the thumbnail `NSCache` so tests read like the
/// dictionary the cache replaced (ISS-106). `NSCache` exposes no subscript and no
/// way to enumerate or count entries, so emptiness is asserted per-key instead.
private extension NSCache where KeyType == NSNumber, ObjectType == NSImage {
    subscript(_ index: Int) -> NSImage? {
        get { object(forKey: index as NSNumber) }
        set {
            if let newValue {
                setObject(newValue, forKey: index as NSNumber)
            } else {
                removeObject(forKey: index as NSNumber)
            }
        }
    }
}

// MARK: - Helpers

/// Creates a view model with a single blank PDF page already loaded.
@MainActor
private func makeViewModelWithSinglePage() -> PDFViewerViewModel {
    let vm = PDFViewerViewModel()
    let doc = PDFDocument()
    doc.insert(PDFPage(), at: 0)
    vm.document = doc
    return vm
}

/// Creates a view model with `count` blank PDF pages already loaded.
@MainActor
private func makeViewModelWithPages(_ count: Int) -> PDFViewerViewModel {
    let vm = PDFViewerViewModel()
    let doc = PDFDocument()
    for i in 0..<count {
        doc.insert(PDFPage(), at: i)
    }
    vm.document = doc
    return vm
}

// MARK: - PDFViewerViewModelTests

@MainActor
struct PDFViewerViewModelTests {

    // MARK: Initial State

    @Test func initialStateHasNilDocument() {
        let vm = PDFViewerViewModel()
        #expect(vm.document == nil)
    }

    @Test func initialPageIndexIsZero() {
        let vm = PDFViewerViewModel()
        #expect(vm.currentPageIndex == 0)
    }

    @Test func initialScaleFactorIsOne() {
        let vm = PDFViewerViewModel()
        #expect(vm.scaleFactor == 1.0)
    }

    @Test func initialFitToWidthIsTrue() {
        let vm = PDFViewerViewModel()
        #expect(vm.isFitToWidth == true)
    }

    @Test func initialRotationIsZero() {
        let vm = PDFViewerViewModel()
        #expect(vm.rotation == 0)
    }

    @Test func initialTOCSidebarIsHidden() {
        let vm = PDFViewerViewModel()
        #expect(vm.isTOCVisible == false)
    }

    @Test func initialThumbnailsSidebarIsHidden() {
        let vm = PDFViewerViewModel()
        #expect(vm.isThumbnailsVisible == false)
    }

    @Test func initialErrorMessageIsNil() {
        let vm = PDFViewerViewModel()
        #expect(vm.errorMessage == nil)
    }

    @Test func initialIsLoadingIsFalse() {
        let vm = PDFViewerViewModel()
        #expect(vm.isLoading == false)
    }

    @Test func initialThumbnailCacheIsEmpty() {
        let vm = PDFViewerViewModel()
        // NSCache has no isEmpty/count; a fresh cache returns nil for any key.
        #expect(vm.thumbnailCache[0] == nil)
    }

    // MARK: totalPageCount

    @Test func totalPageCountZeroWithNoDocument() {
        let vm = PDFViewerViewModel()
        #expect(vm.totalPageCount == 0)
    }

    @Test func totalPageCountReflectsLoadedDocument() {
        let vm = makeViewModelWithPages(5)
        #expect(vm.totalPageCount == 5)
    }

    @Test func totalPageCountUpdatesAfterClose() {
        let vm = makeViewModelWithPages(3)
        vm.closeDocument()
        #expect(vm.totalPageCount == 0)
    }

    // MARK: Zoom In

    @Test func zoomInIncreasesScaleByQuarter() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = false
        vm.scaleFactor = 1.0
        vm.zoomIn()
        #expect(vm.scaleFactor == 1.25)
    }

    @Test func zoomInCapsAtMaxScale() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = false
        vm.scaleFactor = 4.0
        vm.zoomIn()
        #expect(vm.scaleFactor == 4.0)
    }

    @Test func zoomInApproachingMaxClampsCorrectly() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = false
        vm.scaleFactor = 3.75
        vm.zoomIn()
        #expect(vm.scaleFactor == 4.0)
    }

    @Test func zoomInDisablesFitToWidth() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = true
        vm.zoomIn()
        #expect(vm.isFitToWidth == false)
    }

    // MARK: Zoom Out

    @Test func zoomOutDecreasesScaleByQuarter() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = false
        vm.scaleFactor = 1.0
        vm.zoomOut()
        #expect(vm.scaleFactor == 0.75)
    }

    @Test func zoomOutFloorsAtMinScale() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = false
        vm.scaleFactor = 0.25
        vm.zoomOut()
        #expect(vm.scaleFactor == 0.25)
    }

    @Test func zoomOutApproachingMinClampsCorrectly() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = false
        vm.scaleFactor = 0.5
        vm.zoomOut()
        #expect(vm.scaleFactor == 0.25)
    }

    @Test func zoomOutDisablesFitToWidth() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = true
        vm.zoomOut()
        #expect(vm.isFitToWidth == false)
    }

    // MARK: Toggle Fit To Width

    @Test func toggleFitToWidthFromFitSwitchesToManual() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = true
        vm.toggleFitToWidth()
        #expect(vm.isFitToWidth == false)
    }

    @Test func toggleFitToWidthFromManualSwitchesToFit() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = false
        vm.toggleFitToWidth()
        #expect(vm.isFitToWidth == true)
    }

    @Test func toggleFitToWidthSavesAndRestoresScale() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = false
        vm.scaleFactor = 2.0
        vm.toggleFitToWidth()   // → fit mode, saves 2.0
        vm.toggleFitToWidth()   // → manual mode, restores 2.0
        #expect(vm.scaleFactor == 2.0)
    }

    @Test func toggleFitToWidthDoesNotAlterSavedScaleWhenGoingToFit() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = false
        vm.scaleFactor = 1.75
        vm.toggleFitToWidth()   // saves 1.75
        vm.toggleFitToWidth()   // restores 1.75
        #expect(vm.scaleFactor == 1.75)
    }

    // MARK: Rotation

    @Test func rotateClockwiseAddsNinetyDegrees() {
        let vm = PDFViewerViewModel()
        vm.rotateClockwise()
        #expect(vm.rotation == 90)
    }

    @Test func rotateClockwiseTwiceGives180() {
        let vm = PDFViewerViewModel()
        vm.rotateClockwise()
        vm.rotateClockwise()
        #expect(vm.rotation == 180)
    }

    @Test func rotateClockwiseThreeTimesGives270() {
        let vm = PDFViewerViewModel()
        vm.rotateClockwise()
        vm.rotateClockwise()
        vm.rotateClockwise()
        #expect(vm.rotation == 270)
    }

    @Test func rotateClockwiseFullCycleReturnsToZero() {
        let vm = PDFViewerViewModel()
        vm.rotateClockwise() // 90
        vm.rotateClockwise() // 180
        vm.rotateClockwise() // 270
        vm.rotateClockwise() // 0
        #expect(vm.rotation == 0)
    }

    @Test func rotateClockwiseWrapsAt360() {
        let vm = PDFViewerViewModel()
        vm.rotation = 270
        vm.rotateClockwise()
        #expect(vm.rotation == 0)
    }

    // MARK: Navigation

    @Test func navigateToWithNilDocumentDoesNotCrashAndKeepsZero() {
        let vm = PDFViewerViewModel()
        vm.navigateTo(page: 5)
        #expect(vm.currentPageIndex == 0)
    }

    @Test func navigateToValidPageUpdatesIndex() {
        let vm = makeViewModelWithPages(5)
        vm.navigateTo(page: 3)
        #expect(vm.currentPageIndex == 3)
    }

    @Test func navigateToClampsBelowZeroToFirstPage() {
        let vm = makeViewModelWithPages(3)
        vm.navigateTo(page: -1)
        #expect(vm.currentPageIndex == 0)
    }

    @Test func navigateToBeyondLastPageClampsToLastPage() {
        let vm = makeViewModelWithPages(3)
        vm.navigateTo(page: 10)
        #expect(vm.currentPageIndex == 2)
    }

    @Test func navigateToCallsNavigateAction() {
        let vm = makeViewModelWithPages(5)
        var calledWith: Int? = nil
        vm.navigateAction = { index in calledWith = index }
        vm.navigateTo(page: 2)
        #expect(calledWith == 2)
    }

    @Test func navigateToClampedIndexIsPassedToAction() {
        let vm = makeViewModelWithPages(3)
        var calledWith: Int? = nil
        vm.navigateAction = { index in calledWith = index }
        vm.navigateTo(page: 99)
        #expect(calledWith == 2)
    }

    @Test func navigateNextIncrementsByOne() {
        let vm = makeViewModelWithPages(5)
        vm.currentPageIndex = 2
        vm.navigateNext()
        #expect(vm.currentPageIndex == 3)
    }

    @Test func navigateNextStopsAtLastPage() {
        let vm = makeViewModelWithPages(3)
        vm.currentPageIndex = 2
        vm.navigateNext()
        #expect(vm.currentPageIndex == 2)
    }

    @Test func navigatePreviousDecreasesByOne() {
        let vm = makeViewModelWithPages(5)
        vm.currentPageIndex = 3
        vm.navigatePrevious()
        #expect(vm.currentPageIndex == 2)
    }

    @Test func navigatePreviousStopsAtFirstPage() {
        let vm = makeViewModelWithPages(3)
        vm.currentPageIndex = 0
        vm.navigatePrevious()
        #expect(vm.currentPageIndex == 0)
    }

    // MARK: Error Handling

    @Test func clearErrorSetsMessageToNil() {
        let vm = PDFViewerViewModel()
        vm.errorMessage = "Something went wrong"
        vm.clearError()
        #expect(vm.errorMessage == nil)
    }

    @Test func clearErrorWhenAlreadyNilIsNoop() {
        let vm = PDFViewerViewModel()
        vm.clearError()
        #expect(vm.errorMessage == nil)
    }

    // MARK: Close Document

    @Test func closeDocumentClearsDocument() {
        let vm = makeViewModelWithSinglePage()
        vm.closeDocument()
        #expect(vm.document == nil)
    }

    @Test func closeDocumentResetsPageIndexToZero() {
        let vm = makeViewModelWithPages(5)
        vm.currentPageIndex = 3
        vm.closeDocument()
        #expect(vm.currentPageIndex == 0)
    }

    @Test func closeDocumentResetsScaleFactorToOne() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = false
        vm.scaleFactor = 2.5
        vm.closeDocument()
        #expect(vm.scaleFactor == 1.0)
    }

    @Test func closeDocumentRestoresFitToWidthTrue() {
        let vm = PDFViewerViewModel()
        vm.isFitToWidth = false
        vm.closeDocument()
        #expect(vm.isFitToWidth == true)
    }

    @Test func closeDocumentResetsRotationToZero() {
        let vm = PDFViewerViewModel()
        vm.rotation = 180
        vm.closeDocument()
        #expect(vm.rotation == 0)
    }

    @Test func closeDocumentHidesTOCSidebar() {
        let vm = PDFViewerViewModel()
        vm.isTOCVisible = true
        vm.closeDocument()
        #expect(vm.isTOCVisible == false)
    }

    @Test func closeDocumentHidesThumbnailsSidebar() {
        let vm = PDFViewerViewModel()
        vm.isThumbnailsVisible = true
        vm.closeDocument()
        #expect(vm.isThumbnailsVisible == false)
    }

    @Test func closeDocumentClearsErrorMessage() {
        let vm = PDFViewerViewModel()
        vm.errorMessage = "Corrupted file"
        vm.closeDocument()
        #expect(vm.errorMessage == nil)
    }

    @Test func closeDocumentSetsIsLoadingFalse() {
        let vm = PDFViewerViewModel()
        vm.isLoading = true
        vm.closeDocument()
        #expect(vm.isLoading == false)
    }

    @Test func closeDocumentClearsThumbnailCache() {
        let vm = makeViewModelWithSinglePage()
        vm.thumbnailCache[0] = NSImage()
        vm.closeDocument()
        #expect(vm.thumbnailCache[0] == nil)
    }

    // MARK: Thumbnail Generation

    @Test func generateThumbnailWithNilDocumentDoesNotCrash() {
        let vm = PDFViewerViewModel()
        vm.generateThumbnail(for: 0)
        #expect(vm.thumbnailCache[0] == nil)
    }

    @Test func generateThumbnailForOutOfBoundsIndexDoesNotCrash() {
        let vm = makeViewModelWithSinglePage()
        vm.generateThumbnail(for: 99)
        #expect(vm.thumbnailCache[99] == nil)
    }

    @Test func generateThumbnailSkipsWhenAlreadyCached() {
        let vm = makeViewModelWithSinglePage()
        let sentinel = NSImage()
        vm.thumbnailCache[0] = sentinel
        vm.generateThumbnail(for: 0)
        // The existing image must not be replaced by a new task.
        #expect(vm.thumbnailCache[0] === sentinel)
    }

    // MARK: Async Loading

    @Test func loadPDFSetsErrorForNonExistentURL() async {
        let vm = PDFViewerViewModel()
        let badURL = URL(fileURLWithPath: "/tmp/sputnik_test_nonexistent_\(UInt64.random(in: 1...99999)).pdf")
        await vm.loadPDF(badURL)
        #expect(vm.errorMessage != nil)
        #expect(vm.isLoading == false)
    }

    @Test func loadPDFResetsPageIndexBeforeLoad() async {
        let vm = PDFViewerViewModel()
        vm.currentPageIndex = 3
        let badURL = URL(fileURLWithPath: "/tmp/sputnik_test_nonexistent_b.pdf")
        await vm.loadPDF(badURL)
        #expect(vm.currentPageIndex == 0)
    }

    @Test func loadPDFClearsThumbnailCacheBeforeLoad() async {
        let vm = PDFViewerViewModel()
        vm.thumbnailCache[0] = NSImage()
        let badURL = URL(fileURLWithPath: "/tmp/sputnik_test_nonexistent_c.pdf")
        await vm.loadPDF(badURL)
        #expect(vm.thumbnailCache[0] == nil)
    }

    @Test func loadPDFResetsRotationBeforeLoad() async {
        let vm = PDFViewerViewModel()
        vm.rotation = 90
        let badURL = URL(fileURLWithPath: "/tmp/sputnik_test_nonexistent_d.pdf")
        await vm.loadPDF(badURL)
        #expect(vm.rotation == 0)
    }

    @Test func loadPDFIsNoOpWhenAlreadyLoading() async {
        let vm = PDFViewerViewModel()
        vm.isLoading = true
        let url = URL(fileURLWithPath: "/tmp/sputnik_test_e.pdf")
        await vm.loadPDF(url)
        // Early return — errorMessage stays nil since we did not attempt a load.
        #expect(vm.errorMessage == nil)
    }

    @Test func retryLoadIsNoOpWhenNoPreviousURLSet() async {
        let vm = PDFViewerViewModel()
        await vm.retryLoad()
        #expect(vm.document == nil)
        #expect(vm.errorMessage == nil)
    }

    @Test func loadImageSetsErrorForNonExistentURL() async {
        let vm = PDFViewerViewModel()
        let badURL = URL(fileURLWithPath: "/tmp/sputnik_test_nonexistent_img.png")
        await vm.loadImage(badURL)
        #expect(vm.errorMessage != nil)
        #expect(vm.isLoading == false)
    }

    @Test func loadImageResetsStateBeforeLoad() async {
        let vm = PDFViewerViewModel()
        vm.rotation = 90
        vm.currentPageIndex = 2
        let badURL = URL(fileURLWithPath: "/tmp/sputnik_test_nonexistent_img2.jpg")
        await vm.loadImage(badURL)
        #expect(vm.currentPageIndex == 0)
        #expect(vm.rotation == 0)
    }

    @Test func loadImageIsNoOpWhenAlreadyLoading() async {
        let vm = PDFViewerViewModel()
        vm.isLoading = true
        let url = URL(fileURLWithPath: "/tmp/sputnik_test_img3.png")
        await vm.loadImage(url)
        #expect(vm.errorMessage == nil)
    }
}
