// MarkdownPreviewModuleTests.swift
// Generated by !CreateTests skill — review before merging

import Testing
@testable import MarkdownPreviewModule
import AppKit
import Foundation

// MARK: - MarkdownPreviewViewModelTests

/// Tests for `MarkdownPreviewViewModel` — the `@Observable @MainActor` class that owns
/// the rendered output, fontScale preference, scroll position, and render-pipeline state.
///
/// All tests run on the main actor to match the class's isolation requirement.
/// The render pipeline itself is async (background Task + RenderThrottle); tests here
/// only verify the synchronous effects of calling `render()` — namely that `isRendering`
/// is set to `true` and `renderError` is cleared. Full render-completion assertions
/// require integration tests (see summary).
@MainActor
struct MarkdownPreviewViewModelTests {

    // MARK: Happy Path — initial state

    @Test func initialRenderedStringIsEmpty() {
        let vm = MarkdownPreviewViewModel()
        #expect(vm.renderedString.length == 0)
    }

    @Test func initialScrollOffsetIsZero() {
        let vm = MarkdownPreviewViewModel()
        #expect(vm.scrollOffset == 0)
    }

    @Test func initialFontScaleIsOne() {
        let vm = MarkdownPreviewViewModel()
        #expect(vm.fontScale == 1.0)
    }

    @Test func initialIsRenderingIsFalse() {
        let vm = MarkdownPreviewViewModel()
        #expect(vm.isRendering == false)
    }

    @Test func initialRenderErrorIsNil() {
        let vm = MarkdownPreviewViewModel()
        #expect(vm.renderError == nil)
    }

    // MARK: Edge Cases — fontScale clamping (didSet enforces 0.5 ... 2.0)

    @Test func fontScaleZeroClampedToMinimum() {
        let vm = MarkdownPreviewViewModel()
        vm.fontScale = 0.0
        #expect(vm.fontScale == 0.5)
    }

    @Test func fontScaleNegativeClampedToMinimum() {
        let vm = MarkdownPreviewViewModel()
        vm.fontScale = -1.0
        #expect(vm.fontScale == 0.5)
    }

    @Test func fontScaleBelowMinimumClamped() {
        let vm = MarkdownPreviewViewModel()
        vm.fontScale = 0.3
        #expect(vm.fontScale == 0.5)
    }

    @Test func fontScaleAtMinimumBoundaryUnchanged() {
        let vm = MarkdownPreviewViewModel()
        vm.fontScale = 0.5
        #expect(vm.fontScale == 0.5)
    }

    @Test func fontScaleAtDefaultUnchanged() {
        let vm = MarkdownPreviewViewModel()
        vm.fontScale = 1.0
        #expect(vm.fontScale == 1.0)
    }

    @Test func fontScaleAtMidRangeUnchanged() {
        let vm = MarkdownPreviewViewModel()
        vm.fontScale = 1.5
        #expect(vm.fontScale == 1.5)
    }

    @Test func fontScaleAtMaximumBoundaryUnchanged() {
        let vm = MarkdownPreviewViewModel()
        vm.fontScale = 2.0
        #expect(vm.fontScale == 2.0)
    }

    @Test func fontScaleAboveMaximumClamped() {
        let vm = MarkdownPreviewViewModel()
        vm.fontScale = 2.5
        #expect(vm.fontScale == 2.0)
    }

    @Test func fontScaleFarAboveMaximumClamped() {
        let vm = MarkdownPreviewViewModel()
        vm.fontScale = 100.0
        #expect(vm.fontScale == 2.0)
    }

    // MARK: State Mutations

    @Test func scrollOffsetCanBeUpdated() {
        let vm = MarkdownPreviewViewModel()
        vm.scrollOffset = 42.5
        #expect(vm.scrollOffset == 42.5)
    }

    @Test func scrollOffsetCanBeReset() {
        let vm = MarkdownPreviewViewModel()
        vm.scrollOffset = 100.0
        vm.scrollOffset = 0.0
        #expect(vm.scrollOffset == 0.0)
    }

    @Test func renderedStringCanBeSetDirectly() {
        let vm = MarkdownPreviewViewModel()
        let str = NSAttributedString(string: "Hello Markdown")
        vm.renderedString = str
        #expect(vm.renderedString.string == "Hello Markdown")
    }

    @Test func renderErrorCanBeSet() {
        let vm = MarkdownPreviewViewModel()
        vm.renderError = "Parse failed"
        #expect(vm.renderError == "Parse failed")
    }

    @Test func renderErrorCanBeCleared() {
        let vm = MarkdownPreviewViewModel()
        vm.renderError = "Some error"
        vm.renderError = nil
        #expect(vm.renderError == nil)
    }

    // MARK: Render — synchronous effects
    // The pipeline is async internally. These tests verify the effects that happen
    // synchronously at the moment render() is called, before any Task yields.

    @Test func renderSetsIsRenderingTrue() {
        let vm = MarkdownPreviewViewModel()
        vm.render(markdown: "# Hello")
        #expect(vm.isRendering == true)
    }

    @Test func renderClearsRenderErrorSynchronously() {
        let vm = MarkdownPreviewViewModel()
        vm.renderError = "stale error"
        vm.render(markdown: "# Hello")
        #expect(vm.renderError == nil)
    }

    @Test func renderForwarderNoBaseDirSetsIsRendering() {
        let vm = MarkdownPreviewViewModel()
        vm.render(markdown: "**bold**")
        #expect(vm.isRendering == true)
    }

    @Test func renderFontScaleForwarderSetsIsRendering() {
        let vm = MarkdownPreviewViewModel()
        vm.render(markdown: "test", fontScale: 1.5)
        #expect(vm.isRendering == true)
    }
}

// MARK: - MarkdownPreviewCoordinatorTests

/// Tests for `MarkdownPreviewCoordinator` — the `@MainActor NSTextViewDelegate` that
/// routes link clicks and injects "More Context" items into the right-click menu.
///
/// Link click tests call the delegate method directly with a dummy `NSTextView(frame:.zero)`.
/// The coordinator's `clickedOnLink` implementation does not use the text view parameter —
/// only `link` and `linksEnabled` are read — so a minimal NSTextView suffices.
///
/// Note: `http`/`https`/`mailto` click tests call `NSWorkspace.shared.open()` as a side
/// effect; in a headless test environment this is a no-op. The assertion is the return
/// value (`true` = link handled, do not fall through to the system default).
@MainActor
struct MarkdownPreviewCoordinatorTests {

    // MARK: Happy Path — initial state

    @Test func initialLinksEnabledIsTrue() {
        let c = MarkdownPreviewCoordinator(router: nil)
        #expect(c.linksEnabled == true)
    }

    @Test func initialRouterIsNil() {
        let c = MarkdownPreviewCoordinator(router: nil)
        #expect(c.router == nil)
    }

    @Test func initialOnRequestHelpIsNil() {
        let c = MarkdownPreviewCoordinator(router: nil)
        #expect(c.onRequestHelp == nil)
    }

    @Test func initialHelpContextResolverIsNil() {
        let c = MarkdownPreviewCoordinator(router: nil)
        #expect(c.helpContextResolver == nil)
    }

    // MARK: Happy Path — link click routing (return value asserts)

    @Test func clickedHttpLinkReturnsTrue() {
        let c = MarkdownPreviewCoordinator(router: nil)
        let url = URL(string: "http://example.com")!
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: url, at: 0)
        #expect(handled == true)
    }

    @Test func clickedHttpsLinkReturnsTrue() {
        let c = MarkdownPreviewCoordinator(router: nil)
        let url = URL(string: "https://example.com/page")!
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: url, at: 0)
        #expect(handled == true)
    }

    @Test func clickedMailtoLinkReturnsTrue() {
        let c = MarkdownPreviewCoordinator(router: nil)
        let url = URL(string: "mailto:user@example.com")!
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: url, at: 0)
        #expect(handled == true)
    }

    @Test func clickedFileLinkReturnsTrueWithNilRouter() {
        // file:// links fire an async router call (fire-and-forget) — the return value
        // is true regardless of whether a router is wired.
        let c = MarkdownPreviewCoordinator(router: nil)
        let url = URL(string: "file:///Users/test/readme.md")!
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: url, at: 0)
        #expect(handled == true)
    }

    // MARK: Edge Cases

    @Test func clickedLinkWhenLinksDisabledAlwaysReturnsTrue() {
        // linksEnabled=false → return true immediately without routing.
        let c = MarkdownPreviewCoordinator(router: nil)
        c.linksEnabled = false
        let url = URL(string: "https://example.com")!
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: url, at: 0)
        #expect(handled == true)
    }

    @Test func clickedNSURLLinkExtractsURL() {
        let c = MarkdownPreviewCoordinator(router: nil)
        let nsurl = NSURL(string: "https://example.com")!
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: nsurl, at: 0)
        #expect(handled == true)
    }

    @Test func clickedStringLinkExtractsURL() {
        let c = MarkdownPreviewCoordinator(router: nil)
        let str: Any = "https://example.com"
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: str, at: 0)
        #expect(handled == true)
    }

    @Test func clickedUnrecognizedLinkTypeReturnsFalse() {
        // When link is not URL, NSURL, or String, the URL extraction returns nil → false.
        let c = MarkdownPreviewCoordinator(router: nil)
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: 42, at: 0)
        #expect(handled == false)
    }

    @Test func clickedRelativePathWithNoSchemeReturnsFalse() {
        // A URL with no scheme component — guard on url.scheme returns false.
        let c = MarkdownPreviewCoordinator(router: nil)
        guard let url = URL(string: "relative/path.html") else { return }
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: url, at: 0)
        #expect(handled == false)
    }

    // MARK: Error Conditions — unsafe scheme blocking

    @Test func clickedJavascriptLinkBlockedReturnsTrue() {
        // Must return true (handled=blocked) so NSTextView does not fall through
        // to the system handler and call NSWorkspace.open on a javascript: URL.
        let c = MarkdownPreviewCoordinator(router: nil)
        let url = URL(string: "javascript:alert(1)")!
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: url, at: 0)
        #expect(handled == true)
    }

    @Test func clickedDataLinkBlockedReturnsTrue() {
        let c = MarkdownPreviewCoordinator(router: nil)
        let url = URL(string: "data:text/html,<h1>test</h1>")!
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: url, at: 0)
        #expect(handled == true)
    }

    @Test func clickedBlobLinkBlockedReturnsTrue() {
        let c = MarkdownPreviewCoordinator(router: nil)
        let url = URL(string: "blob:some-uuid-1234")!
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: url, at: 0)
        #expect(handled == true)
    }

    @Test func clickedFtpLinkBlockedReturnsTrue() {
        // ftp:// is an unknown scheme — blocked and logged.
        let c = MarkdownPreviewCoordinator(router: nil)
        let url = URL(string: "ftp://ftp.example.com/file.txt")!
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: url, at: 0)
        #expect(handled == true)
    }

    @Test func clickedCustomSchemeBlockedReturnsTrue() {
        let c = MarkdownPreviewCoordinator(router: nil)
        let url = URL(string: "myapp://open/document")!
        let handled = c.textView(NSTextView(frame: .zero), clickedOnLink: url, at: 0)
        #expect(handled == true)
    }

    // MARK: Context Menu — empty / whitespace selection

    @Test func contextMenuUnchangedForZeroLengthSelection() {
        // Empty selection → no More Context items → original menu returned unchanged.
        let c = MarkdownPreviewCoordinator(router: nil)
        let textView = NSTextView(frame: .zero)
        textView.string = "Hello world"
        let menu = NSMenu()
        menu.addItem(NSMenuItem(title: "Copy", action: nil, keyEquivalent: "c"))

        let result = c.textView(
            textView, menu: menu, at: 0, for: NSRange(location: 0, length: 0))
        #expect(result?.numberOfItems == 1)
    }

    @Test func contextMenuUnchangedForWhitespaceOnlySelection() {
        // Whitespace-only selection trims to empty → no More Context items.
        let c = MarkdownPreviewCoordinator(router: nil)
        let textView = NSTextView(frame: .zero)
        let whitespace = "   "
        textView.string = whitespace
        let menu = NSMenu()
        menu.addItem(NSMenuItem(title: "Copy", action: nil, keyEquivalent: "c"))

        let result = c.textView(
            textView, menu: menu, at: 0,
            for: NSRange(location: 0, length: (whitespace as NSString).length))
        #expect(result?.numberOfItems == 1)
    }
}
